### ISSUE TITLE
save tweet contents to a text file

### ISSUE THREAD

**Issue by arceuss** [JustAnotherArchivist/snscrape#102]
i am scraping someones tweets for ai but idk how to make it just the tweet content

**Comment by arceuss** [comment]
`

    import jsonlines

    tweets = []

    with jsonlines.open('foo.txt') as reader:
    for obj in reader:
    tweets.append(obj["content"])
`
this is what im using btw

**Comment by JustAnotherArchivist** [comment]
If you just want pure content and don't care about tweets with line breaks getting split, `--format '{content}'` will do. If you need to preserve the line breaks, you could perhaps get away with `--format '{content!r}'`, but using that can get messy quickly. Otherwise, use the API (see #73 for an example) and write out the data directly in the format you need it.

**Comment by arceuss** [comment]
snscrape: error: argument --jsonl: not allowed with argument -f/--format ?

**Comment by arceuss** [comment]
oh i got it to work but it just has issues with unicode and stuff begins and ends with '

**Comment by JustAnotherArchivist** [comment]
That's the Python string representation format. You can use [`ast.literal_eval`](https://docs.python.org/3/library/ast.html#ast.literal_eval) to convert it to a string object again as needed, e.g.

```python
import ast
with open('filename', 'r') as fp:
	for line in fp:
		content = ast.literal_eval(line.strip())
		# Do something with content
```

**Comment by ihahawen** [comment]
> snscrape：错误：参数--jsonl：参数-f /-format不允许？

How did you solve it

**Comment by ihahawen** [comment]
> snscrape: error: argument --jsonl: not allowed with argument -f/--format ?

How did you solve it

**Comment by JustAnotherArchivist** [comment]
@ihahawen Only use either `--jsonl` or `--format` but not both at once.

**Comment by ihahawen** [comment]
> @ihahawen Only use either `--jsonl` or `--format` but not both at once.
i can use --jsonl,but i can't use --format,something mistake
PS C:\Users\MSI\Documents\GitHub\snscrape> snscrape twitter-search 'from:realDonaldTrump since:2020-10-01 until:2020-10-08' --format '{content}'
usage: snscrape [-h] [--version] [-v] [--dump-locals] [--retry N] [-n N] [-f FORMAT | --jsonl] [--with-entity] [--since DATETIME]
                {telegram-channel,vkontakte-user,weibo-user,facebook-group,instagram-user,instagram-hashtag,instagram-location,reddit-user,reddit-subreddit,reddit-search,twitter-thread,twitter-search,facebook-user,facebook-community,twitter-user,twitter-hashtag,twitter-list-posts,twitter-profile} ...
snscrape: error: unrecognized arguments: --format {content}

**Comment by JustAnotherArchivist** [comment]
@ihahawen `--format` is a global option, so it must come before the scraper (as the error message indicates; `-f` = `--format`):

    snscrape --format '{content}' twitter-search 'from:realDonaldTrump since:2020-10-01 until:2020-10-08'

**Comment by ihahawen** [comment]
Thank you very much,so thats，I can't put it in the end
