### ISSUE TITLE
Extract data from json file

### ISSUE THREAD

**Issue by KeithLenders** [JustAnotherArchivist/snscrape#104]
Hi
I have got json file from snscrape and am trying to extract data from this file.  I can display the following correctly using:

import json

with open('out.json', 'r') as json_file:
    for line in json_file:
        data = json.loads(line)
        print(data['date']+' - '+data['username']+' - '+data['content']+'\n')

but say if i try to print any data from the json file eg) 'media__fullUrl' or 'user__followersCount' i get an error regarding the double underscore __

Can anybody help thanks

**Comment by JustAnotherArchivist** [comment]
No clue where you got that idea, but there are no underscores in the object keys. `data['user']` is a normal object again, for example. So use e.g. `data['user']['followersCount']`.

**Comment by KeithLenders** [comment]
ok thanks, i did convert the json file to a csv file, that must be wehere it added the underscores.  I am able to print the follower count now but i am still unable to print the fullUrl to any pictures/videos that were in a tweet.

**Comment by JustAnotherArchivist** [comment]
1. `data['media']` is a list. If there are no media on a tweet, it's `None` (in Python) or `null` (in JSON).
2. The structure of the elements within that list depends on what it is: a photo, a video, or a GIF. The `fullUrl` field only exists for photos. Check the `type` field on each medium entry.

So if you only care about photos:

```python
if data['media']:
	for medium in data['media']:
		if medium['type'] == 'photo':
			# Do something with medium['fullUrl']
```

**Comment by KeithLenders** [comment]
thats great, thank you for your help, i can now print out the photo links. i am still learning but this helps a lot.

It really is a great project you have.

**Comment by JustAnotherArchivist** [comment]
Yes, videos and GIFs are also in `data['media']` with `type` values of `'video'` and `'gif'`, respectively. They're otherwise the same, except that the `duration` key only exists for videos. ('GIFs' on Twitter are actually just videos without sound, without the duration exposed, and with looping.) The `variants` key contains the different video versions with a content type, a URL, and the bitrate if known.

I think these should also be present for quoted and retweeted tweets, but I haven't verified in detail. I'm pretty sure they aren't returned for nested quotes.

**Comment by KeithLenders** [comment]
ok i see. i am now able to print the urls for the video media using the code below.  the urls will display fine in the command prompt window, but if i try to write them to a file the urls have odd breaks in which "break" the link if i try to download them with urllib. this being what i am trying to achieve.
```
        if data['media']:
            for medium in data['media']:
                if medium['type'] == 'video':
                    vid = medium['variants'][0]['url'].strip()
                    with open('vid.txt', 'a') as f:
                        f.write(vid)
                        f.close()
```

here is an extract of how the urls look in the text file output. i have tried stripping any whitespace after each line and still get the same result.  thanks again for helping me out with this.

`https://video.twimg.com/amplify_video/1313757599477633026/vid/320x400/aiRcfZKZVfWledx9.mp4?tag=13https://video.twimg.com/amplify_video/1313340265130717184/vid/360x450/G727zdjoVtkb4m3r.mp4?tag=13https://video.twimg.com/amplify_video/1312041940146241537/pl/Y53x10Bu7yD2JF8B.m3u8?tag=13https://video.twimg.com/amplify_video/1311219503615758336/pl/1C7UwwdpqbSOpvuD.m3u8?tag=13https://video.twimg.com/amplify_video/1310723188918083584/vid/320x320/uWEVHKEY-urb_Zbe.mp4?tag=13https://video.twimg.com/ext_tw_video/1308716467706306565/pu/vid/360x640/q6416A_qTBmUPeNB.mp4?tag=10https://video.twimg.com/amplify_video/1309444927298834433/vid/320x566/Ml-gAm75NN1JHZIx.mp4?tag=13https://video.twimg.com/amplify_video/1309049902803152896/vid/576x1138/hN_S9a2blXfNkKOc.mp4?
`

**Comment by JustAnotherArchivist** [comment]
This is getting off-topic now, but a few comments regardless:

* You'll have to figure out which variant you want to grab as Twitter offers various resolutions and at least two formats.
* If you want to download anything based on M3U8, it gets more complicated since you'll have to parse that, download the individual segments, and then combine them into one video file again. I believe there are packages which can do that for you though.
* For the actual download (if not using some package for M3U8 which does it for you), I'd suggest using [Requests](https://requests.readthedocs.io/en/master/). snscrape uses it as well under the hood, so you'll already have it installed. Please refer to the linked documentation on how to use it (or urllib's if you insist on using that).

But since this is no longer about using snscrape or the format of its output, I'm closing this issue.

**Comment by ihahawen** [comment]
`"media": [{"thumbnailUrl": "https://pbs.twimg.com/amplify_video_thumb/1316163917698289664/img/mzkIrk-jpVp6NWvb.jpg", "variants": [{"contentType": "video/mp4", "url": "https://video.twimg.com/amplify_video/1316163917698289664/vid/480x270/sR9VMVq9wVcXmPWi.mp4?tag=13", "bitrate": 288000}, {"contentType": "video/mp4", "url": "https://video.twimg.com/amplify_video/1316163917698289664/vid/640x360/JPJw8UhanJQ4SJ5S.mp4?tag=13", "bitrate": 832000}, {"contentType": "application/x-mpegURL", "url": "https://video.twimg.com/amplify_video/1316163917698289664/pl/aybnMAcOUOHY7hoo.m3u8?tag=13", "bitrate": null}, {"contentType": "video/mp4", "url": "https://video.twimg.com/amplify_video/1316163917698289664/vid/1280x720/wD18FpDdXl7NbbSC.mp4?tag=13", "bitrate": 2176000}], "duration": 48.134, "type": "video"}],`

if i want to get the video,which one i choose?

**Comment by ihahawen** [comment]
the video contain “480*270”，“1280*720“，“640*320”，their sequence is change，usually `medium['variants'][0]['url']` is not 1280*720，how can i get the clearest video？
