### ISSUE TITLE
Ensure all Posts for a given period - Resume Scrape??

### ISSUE THREAD

**Issue by JarBinks** [JustAnotherArchivist/snscrape#132]
Hello, recently moved from another project, to remain unnamed, and love SNScrape.

I have a situation where I am searching twitter for a keyword which has lots of activity, lets say COVID :-(.
Even if I get the max, I am not likely to get all posts. (Especially if this is the first pull of it)
I can pull it frequently but that does not guarantee I know what I am missing and know how to get it.

Some ideas:  --since (But does not have a time component and I would need a --until also), _cursor (I do not understand how to use it)

Some background:
  We have a Python based scheduling architecture that spawns many scraping jobs/threads and uses proxies to avoid banning.
  I prefer to keep each job small to ensure quick results. Usually less than 300 results, more likely 100.
  We are using SNScrape directly from Python, not command line.
  We have good experience and lots of flexibility in how we build and control the jobs.

Any insight/ideas that can be provided would be appreciated.

**Comment by JustAnotherArchivist** [comment]
In principle, you should get all tweets on one scrape – assuming Twitter doesn't break and causes snscrape to crash.

On Twitter, it's best to use the `since` and `until` search filters, cf. #81. The `--cursor` option mostly exists to recover from crashes but generally shouldn't be used (and I'm considering hiding it from the help for that reason). Another option would be using `max_id`, see #80.
For other social networks, it isn't possible to filter this way.

**Comment by JarBinks** [comment]
Thanks for the links to the more info.

We will not use the cursor now that I better understand what that is and does not useful to our situation.

I am still a little unsure on how to proceed but that gives me confidence to try a few things.

Thanks

**Comment by JustAnotherArchivist** [comment]
One more thing I glossed over before: scraping only a couple hundred tweets at once is very inefficient due to the token generation. I would recommend doing it in chunks of at least a few thousand tweets.

**Comment by JarBinks** [comment]
Now we have alot going on in our scraper, proxy, DB interaction, etc..  so what I am about to say might be related to other things.

When I increased from 100 to 300 tweets, I saw times go from 30secs to 5 mins for a single job so I am a little worried about the job time.
However, along with the testing we are doing on the other options we will increase the limits and see how it behaves for us.

Thanks so much for the interactive conversation.

**Comment by JustAnotherArchivist** [comment]
I see. Maybe you can just continuously scrape very slowly (i.e. simply keep iterating over `get_items` and block as necessary for your backend interaction). The token is supposed to stay valid for hours, I think. I never tested this though since I usually try to get the results as quickly as possible and do only light processing or write them always to a file first.
