### ISSUE TITLE
Support for scraping tweet based on its ID

### ISSUE THREAD

**Issue by santoshbs** [JustAnotherArchivist/snscrape#137]
I was wondering if we could use snscrape to fetch the tweet text for a given twitter status id or a set of status ids. I could not find this in the documentation.

**Comment by JustAnotherArchivist** [comment]
There is no explicit support for this at the moment, but I intend to add something that also covers #51 and a reimplementation of #12 (cf. <https://github.com/JustAnotherArchivist/snscrape/issues/98#issuecomment-702736493>).

As a workaround, it's possible to fetch individual tweets through the search using the `since_id` and `max_id` operators. However, you can't use those on their own. But this works, for example:

    snscrape --jsonl twitter-search 'since_id:1320246372008853503 max_id:1320246372008853504 filter:safe'

If that produces no result, put a `-` before the filter:

    snscrape --jsonl twitter-search 'since_id:1303506596216045567 max_id:1303506596216045568 -filter:safe'

The `max_id` is the ID of the tweet of interest, and the `since_id` is one below that; or in other words, `since_id` filters for tweets newer than an ID (not inclusive) and `max_id` filters for tweets older than an ID (inclusive).

Note that this is quite inefficient since you have to run a separate search for every tweet ID. If you have a lot of tweets, this is probably not a good idea. However, my upcoming implementation likely won't fare any better.

**Comment by maclean-alexander** [comment]
Hello, I've been looking for methods to get tweets from a list of IDs and this seems like a workable solution. However, I've noticed that from the list I've been using, less than 20% of the queries return tweet information. Doing manual checking for the IDs, most of them do exist, and I think the differentiating factor is that the tweets not being returned seem to be Retweets. I couldn't find anything that was filtering out retweets, so I was wondering if you knew of a way to get access to the tweets even when they are retweets. I had also tried looking at TwitterThreadScraper, but could not get that working in any capacity. Thank you!

**Comment by JustAnotherArchivist** [comment]
@maclean-alexander See #83 and #8. Basically, it isn't possible to reliably extract information on retweets because Twitter's search doesn't return them. I have not yet found time to look into implementing this, so no idea whether/how this will work with regards to retweets. Also, yes, TwitterThreadScraper is broken (<https://github.com/JustAnotherArchivist/snscrape/issues/98#issuecomment-702736493>).

**Comment by maclean-alexander** [comment]
Ah ok, thank you for the quick response.

**Comment by DV777** [comment]
Hello, I do not want to create a duplicate therefore I'll try to make sure I understood correctly from earlier ISSUES. There is currently no way to scrape the retweets and replies of a specific user when using snscrape ? (I tried including 'from:user include:nativeretweets', using the dev version of the package but it returns "snscrape: error: unrecognized arguments: include:nativeretweets' 'from:username) 

It is strange though, since GOT3 was able to do it before the last twitter update completely obliterated it... :/
I also remember Twint being able to scrape retweets but only in the limit of the API as you mentioned in an earlier topic (7 days, 3200~ most recent tweets).

Am I getting it right ? I am trying to make sense out of it (very limited programming knowledge on my behalf)

**Comment by clohaa** [comment]
How can I scrap data using tweet id with the updated module?

**Comment by JustAnotherArchivist** [comment]
CLI: `snscrape twitter-tweet 20`
Python: `snscrape.modules.twitter.TwitterTweetScraper(20)`

**Comment by Swati-Maste** [comment]
Hey, I want to know, how to get the tweet using the tweet ID

**Comment by Swati-Maste** [comment]
I tried the above python code, it says : AttributeError: module 'snscrape.modules.twitter' has no attribute 'TwitteTweetScraper'

**Comment by TheTechRobo** [comment]
Please make sure you're running Python 3.8 or later and the latest version of snscrape.

**Comment by Swati-Maste** [comment]
Yeah I did. But still!

**Comment by TheTechRobo** [comment]
You spelled it wrong, it's `TwitterTweetScraper`, not `TwitteTweetScraper`

**Comment by Swati-Maste** [comment]
oh yeah, thanks a lot

**Comment by Swati-Maste** [comment]
AttributeError: module 'snscrape.modules.twitter' has no attribute 'TwitterTweetScraper', I'm still getting this error
