### ISSUE TITLE
Questions about the Twitter internals

### ISSUE THREAD

**Issue by Kianizainabadi** [JustAnotherArchivist/snscrape#139]
Hi, I'm writing my own program based on snscrape. But there are some codes I don't understand. 

1) Under what circumstances will `['instruction']['replaceEntry']` appear? Are there any examples?
2) What's the point of `['stopOnEmptyResponse']`? It always returns true.
3) What's `'tombstone'`? Sorry for my poor English, but I really want to understand what it means.

Can someone answer those for me? I'm so grateful.

**Comment by JustAnotherArchivist** [comment]
I don't really remember the details. These are things Twitter returns on the internal API that's used by the website, and they're entirely undocumented of course. I just implemented what works, basically. If you want to dig into the details, I'd suggest adding extensive logging for each of the different cases and saving Twitter's raw responses.

1. Possibly on the live feed updates (what you get when you stay on a search page and scroll to the top again, where it loads new results), but I don't remember.
2. I believe I've seen cases where it wasn't true because some slice of the search index returned no results but there could still be results on later pagination. But I don't remember the details.
3. 'Tombstones' are Twitter's notes on tweets, e.g. the 'glorifying violence' message on [this tweet](https://twitter.com/realDonaldTrump/status/1266231100780744704), which is how I initially discovered them (#63). I believe there are plenty of other cases where these are used, e.g. 'tweet unavailable', but I don't remember the details.

**Comment by Kianizainabadi** [comment]
> I don't really remember the details. These are things Twitter returns on the internal API that's used by the website, and they're entirely undocumented of course. I just implemented what works, basically. If you want to dig into the details, I'd suggest adding extensive logging for each of the different cases and saving Twitter's raw responses.
> 
> 1. Possibly on the live feed updates (what you get when you stay on a search page and scroll to the top again, where it loads new results), but I don't remember.
> 2. I believe I've seen cases where it wasn't true because some slice of the search index returned no results but there could still be results on later pagination. But I don't remember the details.
> 3. 'Tombstones' are Twitter's notes on tweets, e.g. the 'glorifying violence' message on [this tweet](https://twitter.com/realDonaldTrump/status/1266231100780744704), which is how I initially discovered them (#63). I believe there are plenty of other cases where these are used, e.g. 'tweet unavailable', but I don't remember the details.

Thank you so much! Your answer is very helpful to me!😄
