### ISSUE TITLE
Support for pulling top 100 Tweets per hour and running loop for selected amount of days

### ISSUE THREAD

**Issue by ridwan102** [JustAnotherArchivist/snscrape#152]
Is there a way to pull 100 Tweets/hour and set a loop so you designate for how many historical days for it to run?

**Comment by JustAnotherArchivist** [comment]
There are a few aspects here:

* Retrieving top tweets – This is not supported yet and tracked in #109.
* Finding top tweets within an hour – I believe this is impossible directly. Twitter's `since` and `until` filters only accept dates, not datetimes. So the best route I can think of is retrieving the top tweets of a day until you have 100 results in each hour.
* Looping over days – This would have to happen outside of snscrape. While you could potentially combine this with the previous point, i.e. retrieve the top tweets over multiple days at once and group by each hour window until you have 100 in each, this might be less efficient depending on how many days you're looking to cover.

The functionality you're looking for is too specific to be implemented into snscrape. I have no intention of adding aggregations in general actually because there are simply too many possible ways to aggregate results. Instead, snscrape focuses on the scraping and content extraction, and then aggregations of any kind can be done externally.

**Comment by JustAnotherArchivist** [comment]
See #259 for filtering based on Epoch timestamps instead of dates by using `since_time` and `until_time`.
