### ISSUE TITLE
Including only tweets and replies of user

### ISSUE THREAD

**Issue by UditArora2000** [JustAnotherArchivist/snscrape#193]
```
def get_all_tweets(alltweets, screen_name, curr_key, pos, start_date, end_date):
	u_tweets = []
	for i,tweet in enumerate(snt.TwitterUserScraper(f'{screen_name} since:{start_date} until:{end_date}').get_items()):
		u_tweets.append([tweet.date, tweet.id, tweet.content, tweet.username])

```
So I am trying to get tweets and replies for a given user. From what it seems like (I may be wrong) this is giving only tweets, what changes should I make to include in replies as well? Any help would be really appreciated. Thanks!!

**Comment by UditArora2000** [comment]
I think replies are included too. Could someone confirm this?

**Comment by JustAnotherArchivist** [comment]
Yes, the Twitter search returns both original tweets and replies (but not retweets).

Side note: `TwitterUserScraper` is not intended to be used this way; its argument should only be the username. To add more filters, use e.g. `TwitterSearchScraper(f'from:{screen_name} since:{start_date} until:{end_date})` instead.

**Comment by UditArora2000** [comment]
Thanks for the confirmation and the side note.
