### ISSUE TITLE
The number constraint of snscrape in twitter

### ISSUE THREAD

**Issue by Xiaoshu-Zhao** [JustAnotherArchivist/snscrape#225]
Hi

I just wonder if we have the constraint of the number of tweets we scrape if we use snscrape?
here is my code and I just scrape 5 result if I search by "#PublicTransit" and it does not make sense. Anyone can help me with this?

```python
def search_by_text(text = '#reopen', start = '2019-3-1', end = '2021-5-1', radius = '5000km', numberOfTweets = 100):
    scraped_tweets = sntwitter.TwitterSearchScraper(f'{text} since:{start} until:{end} near:"New York"').get_items()
    sliced_scraped_tweets = itertools.islice(scraped_tweets, numberOfTweets)
    tweets_df = pd.DataFrame(sliced_scraped_tweets)
    return tweets_df
```

Thanks!

**Comment by JustAnotherArchivist** [comment]
Geolocation operators, including `near:`, aren't reliable anymore because Twitter deprecated/discontinued geolocation info on tweets in 2019 (cf. #145). I'm getting more results though (`snscrape --jsonl twitter-search '#PublicTransit since:2019-03-01 until:2021-05-01 near:"New York"'`), namely 63. This seems to be correct per [the corresponding web page](https://twitter.com/search?q=%23PublicTransit%20near%3A%22New%20York%22&f=live).

But no, there are no limits on how many tweets a `twitter-search` scrape can return, and I have successfully run scrapes with several million results before. Cf. #69 and #76.

**Comment by Xiaoshu-Zhao** [comment]
> Geolocation operators, including `near:`, aren't reliable anymore because Twitter deprecated/discontinued geolocation info on tweets in 2019 (cf. #145). I'm getting more results though (`snscrape --jsonl twitter-search '#PublicTransit since:2019-03-01 until:2021-05-01 near:"New York"'`), namely 63. This seems to be correct per [the corresponding web page](https://twitter.com/search?q=%23PublicTransit%20near%3A%22New%20York%22&f=live).
> 
> But no, there are no limits on how many tweets a `twitter-search` scrape can return, and I have successfully run scrapes with several million results before. Cf. #69 and #76.

Thanks a lot for your reply! So should I run that code in the terminal? Can I save it as a pd.dataframe and store it in a CSV file?

**Comment by JustAnotherArchivist** [comment]
The CLI only supports text-formatted or JSONL output. `snscrape.modules.twitter.TwitterSearchScraper('#PublicTransit since:2019-03-01 until:2021-05-01 near:"New York"')` should behave identically to my command above, and you get full `Tweet` objects with that. Conversion to other data structures is not something I can help you with.
