### ISSUE TITLE
Instagram hashtag scraper produces empty username field

### ISSUE THREAD

**Issue by rgb-panda** [JustAnotherArchivist/snscrape#234]
Hello,

I'm trying to scrape Instagram hashtags, but in the response I'm getting empty username, and empty taken-by. Is there something I am missing in the command?

snscrape --jsonl --max-results 10 instagram-hashtag oreo > insta-oreo.json

{"_type": "snscrape.modules.instagram.InstagramPost", "cleanUrl": "https://www.instagram.com/p/CPWsFnzD3Yo/", "dirtyUrl": "https://www.instagram.com/p/CPWsFnzD3Yo/?taken-by=", "date": "2021-05-26T23:24:55+00:00", "content": "#need \ud83d\ude0d\ud83d\ude0d\nYall tried this #oreo yet", "thumbnailUrl": "https://instagram.fykz2-1.fna.fbcdn.net/v/t51.2885-15/sh0.08/e35/s640x640/191600095_307513794081369_8524456579598511596_n.jpg?tp=1&_nc_ht=instagram.fykz2-1.fna.fbcdn.net&_nc_cat=109&_nc_ohc=xr8bdeevsPIAX_PeiZi&edm=ABZsPhsBAAAA&ccb=7-4&oh=5dc75bbc88f89b5db73738023895b36d&oe=60B51BEB&_nc_sid=4efc9f", "displayUrl": "https://instagram.fykz2-1.fna.fbcdn.net/v/t51.2885-15/e35/s1080x1080/191600095_307513794081369_8524456579598511596_n.jpg?tp=1&_nc_ht=instagram.fykz2-1.fna.fbcdn.net&_nc_cat=109&_nc_ohc=xr8bdeevsPIAX_PeiZi&edm=ABZsPhsBAAAA&ccb=7-4&oh=8730ce7327d704b7f3145bc9cf79b86b&oe=60B5ACAF&_nc_sid=4efc9f", "username": "", "likes": 0, "comments": 0, "commentsDisabled": false, "isVideo": false}

Thanks,

**Comment by JustAnotherArchivist** [comment]
Unfortunately, it appears that the hashtag HTTP responses no longer include the username at all, only a numeric user ID. Since requesting each post's user individually isn't really an option due to Instagram's ridiculous rate limits, I don't see any way to fix this at the moment.

The fallback value should be `None` (`null` in JSON) though, not an empty string. And the `dirtyUrl` can likely be removed entirely; I don't see those `?taken-by=` URLs appear anywhere anymore.

**Comment by JustAnotherArchivist** [comment]
Closing this as Instagram unfortunately still doesn't return the username on these queries. Nothing I can do about that on the snscrape side.
