### ISSUE TITLE
Cannot search for tweets with query = * or query = #.

### ISSUE THREAD

**Issue by kperveen** [JustAnotherArchivist/snscrape#254]
I am trying to get all tweets between two dates in a language other than English. Right now I have tried removing the query param or adding * or # in place of it. It doesn't seems to work and returns an error. This is code.
`for i,tweet in enumerate(sntwitter.TwitterSearchScraper('# since:2015-01-01 until:2019-07-01').get_items()):
    if i>500:
        break
    print(tweet, [i)`](url)

Error:

Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%23+since%3A2015-01-01+until%3A2019-07-01&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment: non-200 status code, retrying

**Comment by JustAnotherArchivist** [comment]
Yeah, that's not a valid search. Cf. <https://twitter.com/search?q=%23%20since:2015-01-01>, which returns this error:

> This is an invalid search query. Please try a different one.

I'm not going to try to do client-side validation of query strings because that would be unreliable.

As for getting all tweets between two dates, you can try a query like this: `(filter:safe OR -filter:safe) since:2015-01-01 until:2019-07-01`.

**Comment by kperveen** [comment]
Will this return all the tweets or tweets randomly selected

**Comment by kperveen** [comment]
Or is there any way to look only for tweets  between two dates that has hashtags?

**Comment by JustAnotherArchivist** [comment]
It returns 'all' tweets except for the usual exclusions of search-banned users and bugs on Twitter's side (cf. #4).

To get only tweets with hashtags: `filter:hashtags since:2015-01-01 until:2019-07-01`

**Comment by kperveen** [comment]
Is there any way to get trends between two dates? If I do the following, will it return only trending hashtags between those dates?

`filter:trends since:2015-01-01 until:2019-07-01`

**Comment by JustAnotherArchivist** [comment]
I'm not aware of a way to do that. `filter:trends` does not exist. I'm not sure if Twitter even keeps a record of past trends.

Closing this as the original question has been resolved.

**Comment by DaisyWatermelon** [comment]
Hi I tried 
`for i,tweet in enumerate(sntwitter.TwitterSearchScraper('(filter:safe OR -filter:safe) since:2022-02-25 until:2022-03-02').get_items()):` 
and it seems running well, but after 10 mins it shows this error/warning:
`Unsupported card type on tweet 1498810300711292934: '2586390716:message_me'`. I am a bit confused where is this error. Thanks.

**Comment by JustAnotherArchivist** [comment]
That warning is unrelated and just means the card of that tweet couldn't be extracted (i.e. is missing from the output, but the tweet's still there). It also suggests you need to update snscrape because I added support for that card type a while ago.
