### ISSUE TITLE
Fetch historical tweets From protected accounts.

### ISSUE THREAD

**Issue by sufyanhamid** [JustAnotherArchivist/snscrape#257]
hi, @JustAnotherArchivist

Is there a way to scrape the historical tweet of protected users from twitter using snscrape?

Thanks in advance :D

**Comment by JustAnotherArchivist** [comment]
It isn't possible to retrieve tweets from [protected accounts](https://help.twitter.com/en/safety-and-security/public-and-protected-tweets) at all with snscrape because those are only visible to followers of the account and snscrape does not support logging in.

(There are also 'restricted' accounts, where the profile page contents are blocked behind a button. Those accounts' tweets cannot be searched for, so the `twitter-user` scraper doesn't work. You can get the profile page contents with the `twitter-profile` scraper, but that's limited to 3200 results.)

**Comment by sufyanhamid** [comment]
@JustAnotherArchivist thanks for clearing my question. Have a nice week end ;)

**Comment by JustAnotherArchivist** [comment]
You, too!

**Comment by smomen** [comment]
hi @JustAnotherArchivist - I didn't want to post a new issue since it's related to this one. You mentioned we can't access private accounts b/c `snscrape does not support logging in`. Any guidance on how to modify the API usage to do this? Could I inject a custom authorization with my user in the header https://github.com/JustAnotherArchivist/snscrape/blob/master/snscrape/modules/twitter.py#L160 or is there a fundamental limitation in the API (in which case I am stuck scraping html)?

 I'm open to trying and then making an pull request to address this, it's critical to my project anyways. Thank you for all your support.

**Comment by JustAnotherArchivist** [comment]
@smomen Sorry, I have no idea how the API interaction works when logged in – nor whether the search returns tweets from protected accounts or you'd be stuck with the `twitter-profile` scraper. Feel free to play around with it, of course! However, authentication is not something I intend to have in snscrape (cf. #23 and #50).
