### ISSUE TITLE
How to match either of two hashtags in Twitter scrapes?

### ISSUE THREAD

**Issue by kanissh** [JustAnotherArchivist/snscrape#277]
How do I use the command line to scrape tweets that has either of the hashtags specified? 

I need to scrape tweets that have either "#starwars" or "#linux". I used the following command. But this command returns tweets that has both hashtags.
  
`snscrape --jsonl --progress --since 2021-01-01 twitter-hashtag "starwars,linux until:2021-01-31" `

I need to scrape tweets that has either "#starwars" or "#linux". How do I do that?. (Even if both the hashtags are present it is ok)

**Comment by JustAnotherArchivist** [comment]
The `twitter-hashtag` scraper is only intended for a single hashtag and no extra operators; that your command kind of worked should be considered undefined behaviour. Instead, you need to use the more general `twitter-search` instead (which `twitter-hashtag` is based on internally, by the way). For example, to get all tweets with `#starwars` or `#linux` from January:

    snscrape --jsonl twitter-search '(#starwars OR #linux) since:2021-01-01 until:2021-02-01'

(Note that Twitter's `until` filter is exclusive, i.e. this returns tweets posted *before* 1 February. `since`, on the other hand, is inclusive.)

**Comment by kanissh** [comment]
Thank you for your help
