### ISSUE TITLE
multiple search type in CLI mode

### ISSUE THREAD

**Issue by ankitb142** [JustAnotherArchivist/snscrape#279]
Using CLI mode through the OS library, how do I nest my search queries. For example, i have the below search, but also want to add "lang:en" to the query:
`#os.system("snscrape --jsonl --max-results 20 twitter-search 'from:dogecoin'> user-tweets.json")`

**Comment by kanissh** [comment]
I was able to replicate the language option for the hashtag search as below:

Search for tweets with "#linux" that are in italian
` snscrape --jsonl --progress --max-result 150 --since 2021-01-01 twitter-hashtag "linux until:2021-01-03 lang:it" `

Search for tweets with "#linux" that are in english
` snscrape --jsonl --progress --max-result 150 --since 2021-01-01 twitter-hashtag "linux until:2021-01-03 lang:en" `

 I believe a similar approach is possible with twitter-search. Please try adding "lang:it" (italian), "lang:en" (english) as below.(I did not try it)
`#os.system("snscrape --jsonl --max-results 20 twitter-search 'from:dogecoin lang:it'> user-tweets.json")`

**Comment by ankitb142** [comment]
> 
> 
> I was able to replicate the language option for the hashtag search as below:
> 
> Search for tweets with "#linux" that are in italian
> `snscrape --jsonl --progress --max-result 150 --since 2021-01-01 twitter-hashtag "linux until:2021-01-03 lang:it"`
> 
> Search for tweets with "#linux" that are in english
> `snscrape --jsonl --progress --max-result 150 --since 2021-01-01 twitter-hashtag "linux until:2021-01-03 lang:en"`
> 
> I believe a similar approach is possible with twitter-search. Please try adding "lang:it" (italian), "lang:en" (english) as below.(I did not try it)
> `#os.system("snscrape --jsonl --max-results 20 twitter-search 'from:dogecoin lang:it'> user-tweets.json")`

**Comment by ankitb142** [comment]
It throws an error as below:
`snscrape: error: unrecognized arguments: lang:en'`

Looks like it's a limitation as highlighted here:
[https://github.com/igorbrigadir/twitter-advanced-search](url)

**Comment by kanissh** [comment]
@ankitb142 I tried the following, it is working fine.

`snscrape --jsonl --progress --max-result 20 twitter-search "from:ScuderiaFerrari lang:en"`

`snscrape --jsonl --progress --max-result 20 twitter-search "from:ScuderiaFerrari lang:it"`

**Comment by ankitb142** [comment]
are you using double quotation marks? I tried and it throws invalid syntax.

I am also using the os.system() query in the .py file as the query doesnt run on the kernel itself

**Comment by kanissh** [comment]
I used the commands directly in the terminal. I think you have problems in your python code.

**Comment by ankitb142** [comment]
You mean the python terminal? Below is the code I am using 
`import os
#import snscrape.modules.twitter as sntwitter
import pandas as pd
import datetime as dt
import time

# Using OS library to call CLI commands in Python
os.system("snscrape --jsonl --max-results 20 twitter-search 'fromg:dogecoin lang:en'> user-tweets.json")`

**Comment by ankitb142** [comment]
you mean executing the command in python kernel?
Below is the code I am using:
`import os
#import snscrape.modules.twitter as sntwitter
import pandas as pd
import datetime as dt
import time
# Using OS library to call CLI commands in Python
os.system("snscrape --jsonl --max-results 20 twitter-search 'fromg:dogecoin lang:en'> user-tweets.json")`

**Comment by JustAnotherArchivist** [comment]
I recommend using `subprocess` instead if you absolutely need the CLI. You can give it proper arguments as a list rather than having to rely on the shell command parsing and a file object for redirecting the output to a file if needed:

```python3
import subprocess

with open('foobar.jsonl', 'w') as fp:
	p = subprocess.run(['snscrape', '--jsonl', '--max-results', '20', 'twitter-search', 'from:dogecoin lang:en'], stdout = fp, check = True)
```

But if you don't need CLI-only features (like `--with-entity` or `--progress` or dumping variables on errors for debugging), I would recommend using snscrape directly within Python:

```python3
import snscrape.modules.twitter

scraper = snscrape.modules.twitter.TwitterSearchScraper('from:dogecoin lang:en')
with open('foobar.jsonl', 'w') as fp:
	for i, tweet in enumerate(scraper.get_items()):
		print(tweet.json(), file = fp)
		if i >= 20:
			break
```

**Comment by ankitb142** [comment]
When I use the import snscrape.modules.twitter, I get the below error:
`ModuleNotFoundError: No module named 'snscrape.modules'; 'snscrape' is not a package`

**Comment by JustAnotherArchivist** [comment]
Yeah, that's your separate issue #278. The code works with a correct installation.
