### ISSUE TITLE
Twitter search scraper does not reject empty search queries

### ISSUE THREAD

**Issue by ValerianRey** [JustAnotherArchivist/snscrape#290]
snscrape used with twitter-search produces an exception when the search field is a single cashtag (ex. "$ETH").

Note that when clicking on a cashtag on twitter, the url produced is for example "https://twitter.com/search?q=%24ETH&src=cashtag_click" so maybe adding the field "src=cashtag_click" to the url produced by snscrape can make it work.

**Comment by JustAnotherArchivist** [comment]
The problem here is your invocation of snscrape. Note that the `q` parameter in the error report is empty. Your shell expanded `$ETH` because you used that inside double quotes. And because you didn't define that variable, you get an empty string. So you're actually running `snscrape twitter-search ''`. If you use single quotes (at least in standard modern shells like Bash or zsh), i.e. `snscrape twitter-search '$ETH'`, you'll get the correct behaviour. Alternatively, you can escape the dollar sign explicitly, as in `snscrape twitter-search \$ETH`. In other shells, this might be different.

Searching for cashtags works fine, although apparently Twitter also returns some tweets that don't actually have the cashtag.

There is a bug here though: the search scraper should throw an error directly when the query is empty or consists only of whitespace.

**Comment by ValerianRey** [comment]
My bad, thanks for the explanation!
