### ISSUE TITLE
`KeyError: 'legacy'` on `twitter.TwitterUserScraper.entity` when scraping suspended user

### ISSUE THREAD

**Issue by johnHastings772** [JustAnotherArchivist/snscrape#396]
Hi, first of all congrats on this awesome project, I took a look months ago and have just started using it 'seriously' and found the following error when attemping to access userdata from a suspended/deleted account, and I'm not sure if I'm using the library in a wrong way or this is a real bug.

Code to reproduce:

```
user_scrapper = twitter.TwitterUserScraper('medsdeltaonline')
if user_scrapper.entity:
    print(user_scrapper.entity.description)
```

Error:
```
Traceback (most recent call last):
  File "twit_test.py", line 50, in get_user_information_from_user_id
    if user_scrapper.entity:
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/jhastings/twitter_tests/.venv/lib/python3.8/site-packages/snscrape/base.py", line 163, in entity
    return self._get_entity()
  File "/home/jhastings/twitter_tests/.venv/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 796, in _get_entity
    rawDescription = user['legacy']['description']
KeyError: 'legacy'
```

Other suspended/deleted accounts:

https://twitter.com/YogiHeksa
https://twitter.com/CathyLe69208656

Might this have a similar solution as #392?

Thanks for the project and your attention!

**Comment by JustAnotherArchivist** [comment]
Confirmed, and also affects scrapes from a user ID as well as the `TwitterProfileScraper`.

I don't think returning anything makes sense here since there's zero information returned by Twitter apart from the suspension error. There's some value in tweet tombstones because their tweet ID is known and you can have replies to tombstones etc. So including them gives structural information about the scraped tweets that is otherwise unavailable.

In the past, the `entity` attribute (or well, property) would simply have been `None`. This broke due to the switch to a different API endpoint, which clearly returns a different data format on suspended users (despite carrying the same name...). Your code is entirely correct. :-)
