### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by Barbz2** [JustAnotherArchivist/snscrape#430]
I have been working on a code to scrap data from Twitter but it has recently stopped working. Could someone help me understand the bug? I cannot see the issue with it. The only result I have gotten was a pair of square brackets '[]'.

Thank you so much! :)

I used the following code:

```python3
import snscrape.modules.twitter as sntwitter
import pandas as pd
dataSet = []
for x, tweet in enumerate (sntwitter.TwitterSearchScraper('query: hate speech since: 2006-01-01 until:2015-01-01', 'geolocation: Wooler, 28km').get_items()):
    dataSet=pd.DataFrame(tweets_list1, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

print(dataSet)

tweets.df1.to_csv("C:\SNS Scrape\Barbara code\\TweetData001.csv")
```

**Comment by TheTechRobo** [comment]
A pair of square brackets means "nothing". If it had items, it would be `["item1", "item2", "etc"]`

Doing such a search in Twitter's web-app returns no results. Your search might be faulty.

**Comment by JustAnotherArchivist** [comment]
Your arguments for `TwitterSearchScraper` are wrong. It expects a single query string. You probably want this:

```python3
TwitterSearchScraper('hate speech since:2006-01-01 until:2015-01-01 near:Wooler within:28km')
```

The search query syntax isn't an snscrape thing; snscrape just forwards it to Twitter and spits out whatever their servers return. It's the standard search syntax from Twitter, which is poorly documented officially, but [a good unofficial list exists](https://github.com/igorbrigadir/twitter-advanced-search).

That search still returns no results though, presumably because there simply aren't any matches, so you'll have to tweak the query to your likings.

**Comment by octner** [comment]
There is also a space between "since:" and the date "2006-01-01" -- it should be "since:2006-01-01". It is important that there is no space. Had a similar issue, and removing the space did the trick for me. Just follow the way Twitter generates search queries and it all should be fine.
