### ISSUE TITLE
Issue on specific datetime on twitter and instagram

### ISSUE THREAD

**Issue by ZhangWanlin98** [JustAnotherArchivist/snscrape#436]
First of all, thank you for the excellent scraper.

Due to special need, I need to get tweets specific to minute. However, it seems like the apis do not support taking datetime object as a time range. Can I know is there any solution to search by a more specific time unit, such as in minute？

Also, if the time range input is unachievable, I was thinking to filter the result items based on the item date. However, it seems like the result date is already converted to string which contains no time information. Can I know is there any solution to get the datetime item from the scraped result if searching by minute range is not feasible?

**Comment by JustAnotherArchivist** [comment]
Twitter's search has `since_time` and `until_time` operators which take Unix timestamps for filtering.

That aside, snscrape converts all datetime information into aware `datetime.datetime` objects. If you use the (still undocumented) Python layer, you get those directly. Because JSON doesn't support generic objects, it gets converted to an ISO 8601 string there. But that still includes time and timezone information. The exception to this is that Facebook and VK sometimes only return dates for certain things. For those, such filtering would indeed not be possible because the time information is simply not available.

**Comment by ZhangWanlin98** [comment]
Thank you for the response.
It solved my problem.
