### ISSUE TITLE
Unshorten Twitter links automatically

### ISSUE THREAD

**Issue by TheQuinbox** [JustAnotherArchivist/snscrape#439]
Often times, when I scrape tweets, it's to find an old link, but nonetheless, one that would still work. However, because of Twitter's stupid URL shortening, this is nearly impossible. Is it possible to make SNScrape auto-unshorten these URLs?

**Comment by JustAnotherArchivist** [comment]
I'm not entirely sure what you're asking here exactly.

snscrape already provides both the short and full URLs, specifically in the `tcooutlinks` and `outlinks` attributes of the `Tweet` object, respectively. On `User` objects, there's `linkTcourl` and `linkUrl`, respectively.

If you want to resolve a known t.co URL instead, you can just make a request to it with whatever tool you like; it's a simple HTTP 301 redirect (as long as you avoid using a browser-like user agent, then it's an annoying JavaScript thing because of course it is). For example, with requests in Python: `import requests; print(requests.get('https://t.co/3qGkhq3Y6I', allow_redirects = False).headers.get('Location'))`

(If you want to find the tweets that contain a known t.co URL, you can search for it: `snscrape --jsonl twitter-search 'https://t.co/3qGkhq3Y6I'`)

**Comment by JustAnotherArchivist** [comment]
That's just the `renderedContent`, which is exactly what you'd see on the web interface, and long URLs are displayed like that there. The actual URL is in `outlinks`.

**Comment by TheQuinbox** [comment]
Oh oh, I see. Sorry for the confusion.
