### ISSUE TITLE
facebook and instagram scrapper

### ISSUE THREAD

**Issue by raoumairwaheed** [JustAnotherArchivist/snscrape#453]
Hey, I want to scrape Facebook and Instagram using snscrape. but i didn't find any helping material related to facebook and instagram (modules and parameters related information).

can you please share some material related to these platforms?

**Comment by JustAnotherArchivist** [comment]
There isn't really any beyond the general help (see README, all scrapers fundamentally work the same way) and what you can find here in the issues. I haven't used these in a long time because both sites have ridiculous rate limits that render anything beyond a handful of posts practically impossible to scrape, so they might be quite broken by now.
