### ISSUE TITLE
Scraping tweets only from USA

### ISSUE THREAD

**Issue by ricardonunesoliveira** [JustAnotherArchivist/snscrape#460]
![image](https://user-images.githubusercontent.com/62619730/164236275-df4525bb-3185-4b7a-9bf2-b9a3684dda8d.png)

Anyone has an idea for scraping tweets only from USA? I tried to use location ID, but it didn't worked. The "near" feature does not attend my needs because i have to scrape tweets from all over the country, otherwise my sampe will be biased. I tried to select the middle city in the country and combine the features "near" + "within" but it didn't work too... I need this for my masters, if someone could help me, i will be forever gratefull :D

**Comment by ricardonunesoliveira** [comment]
```
import snscrape.modules.twitter as sntwitter
import pandas as pd
# Creating list to append tweet data to
janeiro1_usa = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('vaccine OR covid vaccine since:2021-01-01 until:2021-01-07 \
-filter:mentions -filter:links lang:en').get_items()):
    if i>1000:
        break
    janeiro1_usa.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.lang])

# Creating a dataframe from the tweets list above
janeiro1df_usa= pd.DataFrame(janeiro1_usa, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Language'])

# Display first 5 entries from dataframe
janeiro1df_usa.head(5)
```

I have to scrape 1000 tweets a week from the whole country, so the feature "near" can't make the task. This is needed to make the sample unbiased.

thanks a lot for the return

**Comment by JustAnotherArchivist** [comment]
There is no reliable way to do this.

You could try Twitter's `place` filter. It takes a Place Object ID as a parameter. I happen to know the one for the USA (96683cc9126741d1), but for the more general problem, you'd have to translate location names to those IDs yourself. I'm not aware of any public way of doing this, only through Twitter's official APIs.

Keep in mind though that your sample will be heavily biased anyway because many (most?) tweets are **not** geotagged. Just as a random prominent example, [President Biden has never tweeted from the USA](https://twitter.com/search?q=place%3A96683cc9126741d1%20from%3APOTUS&f=live) according to this filter...
