### ISSUE TITLE
TwitterSearchScraper not picking up all tweets

### ISSUE THREAD

**Issue by ReddSpark1** [JustAnotherArchivist/snscrape#468]
I'm using this within Python. Generally it's a great tool but in my testing I came across the following. I provided the following as the Twitter "handle":
(from:MuesliSwapTeam) until:2022-05-06 since:2022-04-24

It retrieved 3 tweets for me. But when I type this handle [directly into twitter](https://twitter.com/search?q=(from%3AMuesliSwapTeam)%20until%3A2022-05-06%20since%3A2022-04-24&src=typed_query&f=top) I get a lot more than 3 results. 

Is this a bug or am I using it wrong?

**Comment by TheTechRobo** [comment]
Yeah, 90% of the time these problems are caused by [algorithms](https://www.youtube.com/watch?v=qMsH_3cRKeI) and general weirdness. Not always though (e.g. #37).

If it happens again, try waiting a while and/or trying another IP address.

**Comment by dehma01** [comment]
@JustAnotherArchivist 
I have an issue similar to @ReddSpark1.
I scrapped yesterday tweets from a user and when I double checked manually I realized that some tweets were missing. And everytime I rerun my script it is always the same tweets that are missing.

`$ snscrape twitter-search '(from:idexio) until:2022-05-06 since:2022-04-19' | wc -l
6`
When I check manually I count 10 tweets.
These are the missing tweeets : 

> 1518664515608588288
> 1518287131818479616
> 1516846574768427009
> 1516846577809342464

**Comment by dehma01** [comment]
All the missing tweets that I have mentionned above are within the time range AND not included in the output of snscrape.

https://twitter.com/idexio/status/1518664515608588288

**Comment by JustAnotherArchivist** [comment]
I don't get these in a browser on https://twitter.com/search?q=from:idexio%20until:2022-05-06%20since:2022-04-19&f=live either though. So this seems like another Twitter search issue.

**Comment by dehma01** [comment]
I've just checked ... yeah it seems that the Twitter search does not return every tweet.
I suppose now the best option for me is to use twitter-profile ?

**Comment by JustAnotherArchivist** [comment]
Probably, yes. I'm not aware of any other option than these two, anyway.

**Comment by luisvivasg** [comment]
I am having exactly the same problem.  This seems that is not fied yet. It is not retreiveing all tweets.

**Comment by TheTechRobo** [comment]
This likely isn't an snscrape issue. It's a twitter issue.

If you can see the missing tweets when you replicate the search in a browser, open a new issue.

**Comment by ArtemBernatskyy** [comment]
Is there any some generalized set of rules how to avoid this? For example, sometimes when you have `min_faves` and `since` you can get only 10 days of results, but when you change search to manually track `since` in your code it works just fine...
Thx! 
P.S. I understand that it's a twitter problem (probably because of the caching issue, especially with `min_faves`
