### ISSUE TITLE
Twitter Hashtag scraper getting results for only a day (2022-05-31)

### ISSUE THREAD

**Issue by abdallahmohamedabosaif** [JustAnotherArchivist/snscrape#487]
Hello,
I only get results for one day even though I use a start and end date
This is the code I used

Thanks in advance

```python3
tweet_count = 1000
text_query = "Wordle"
since_date = "2021-01-01"
until_date = "2022-05-31"

os.system('snscrape --jsonl --max-results {} --since {} twitter-hashtag "{} until:{}"> text-query-tweets.json'.format(tweet_count, since_date, text_query, until_date))

tweets_df2 = pd.read_json('text-query-tweets.json', lines=True)

tweets_df2.head()
```

**Comment by abdallahmohamedabosaif** [comment]
@JustAnotherArchivist 
Can you help me, sir

**Comment by TheTechRobo** [comment]
If you only have 1,000 maximum results, it will only get 1,000 results. Try increasing (or removing) the limit.

**Comment by abdallahmohamedabosaif** [comment]
Thank you, I know that and tried it
But it only gets 431 tweets
@JustAnotherArchivist

**Comment by TheTechRobo** [comment]
Twitter's search is weird. Try it in your browser. If you get the same result, it isn't snscrape's fault.

On the other hand, you're not supposed to put search queries like `until:` into the TwitterHashtagScraper. If you want to do search, try the TwitterSearchScraper (exposed as `twitter-search ` on the CLI). Check the README for more details on that.

**Comment by abdallahmohamedabosaif** [comment]
Thanks,
I will try it and back to you

**Comment by JJery-web** [comment]
After changing to the developer version, I succeeded.
Thank you very much for your reply. 
I have another question. I found that some users' twitter can not be crawled completely. For example, the result of the following program is 0. But by definition https://twitter.com/DrasticMeasure5 There are twitter content. I don't know why I can't crawl to the content.
---------
import snscrape. modules. twitter
scraper = snscrape. modules. twitter. TwitterSearchScraper('(from:DrasticMeasure5) until:2015-8-13 since:2014-7-21')
print(sum(1 for tweet in scraper.get_items()))
---------
I find this problem similar to:
https://github.com/JustAnotherArchivist/snscrape/issues/468
