### ISSUE TITLE
snscrape.base.ScraperException: 4 requests to...

### ISSUE THREAD

**Issue by muchtoyearn** [JustAnotherArchivist/snscrape#502]
Hello, 
I am trying to use snscrape to just pull some twitter posts. I keep getting this error, however:

snscrape.base.ScraperException: 4 requests to https://twitter.com/i/api/2/timeline/conversation/(from:coinbase)%20until:2022-06-30%20since:2022-04-01.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=20&include_ext_has_birdwatch_notes=false&ext=mediaStats%2ChighlightedLabel failed, giving up.

Been trying different things for hours, not sure what to do. I'm a newer coder so I'm sure this is an easy fix I just can't figure it out. Thanks for any input. Here is the code I'm using for reference --

```python3
import snscrape.modules.twitter
import snscrape.modules.twitter as sntwitter
import pandas as pd

query = "(from:coinbase) until:2022-06-30 since:2022-04-01"
tweets = []
limits = 100

for tweet in sntwitter.TwitterTweetScraper(query).get_items():
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, tweet.user.username, tweet.content])

df = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet'])
print(df)
```

**Comment by JustAnotherArchivist** [comment]
`TwitterTweetScraper` is for scraping a tweet, not a search query. You want `TwitterSearchScraper`.

**Comment by frida96** [comment]
Hello,
I also receive exactly this error,
but I use in my code;
sntwitter.TwitterSearchScraper(query).get_items()
and get this error!!!!
also for trust; in the code above, I replace TwitterTweetScraper with TwitterSearchScraper, and I got the same error.

thank you for checking this.

**Comment by JustAnotherArchivist** [comment]
@frida96 That's a different problem then. This error was specifically caused by using the wrong scraper and hence sending invalid requests to Twitter. Please search the issue tracker; there are various reasons for why it might fail. And if you can't find one that matches your observations, open a separate issue.

**Comment by Ajaxclopidia** [comment]
Hello,
I am trying to use snscrape to just pull some twitter posts. I keep getting this error, however:

ERROR:snscrape.base:Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=UK+Economy&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo: non-200 status code
CRITICAL:snscrape.base:4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=UK+Economy&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo failed, giving up.
---------------------------------------------------------------------------
ScraperException                          Traceback (most recent call last)
[<ipython-input-4-a37af4c929e3>](https://localhost:8080/#) in <module>
      7 limit = 5000
      8 
----> 9 for tweet in snt.TwitterSearchScraper(query).get_items():
     10     # print(vars(tweet))
     11     # break

4 frames
[/usr/local/lib/python3.8/dist-packages/snscrape/base.py](https://localhost:8080/#) in _request(self, method, url, params, data, headers, timeout, responseOkCallback, allowRedirects, proxies)
    215                         msg = f'{self._retries + 1} requests to {req.url} failed, giving up.'
    216                         logger.fatal(msg)
--> 217                         raise ScraperException(msg)
    218                 raise RuntimeError('Reached unreachable code')
    219 

ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=UK+Economy&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo failed, giving up.

Here is the code I'm using for reference --
import snscrape.modules.twitter as snt
import twitter_scraper
import pandas as pd

query = "UK Economy"
tweets = []
limit = 5000

for tweet in snt.TwitterSearchScraper(query).get_items():
    # print(vars(tweet))
    # break
    
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, tweet.user.username, tweet.likeCount, tweet.sourceLabel,  tweet.content])

tweet_data = pd.DataFrame(tweets, columns=["Date", "User", "Number of likes", "Tweeted from", "Tweets"])
print(tweet_data.head())

tweet_data.to_csv('uk_economy.csv', index = None)

**Comment by EKANSHironfist** [comment]
ScraperException                          Traceback (most recent call last)
Input In [5], in <cell line: 7>()
      5 limit=1000000
      7 for quer in query:
----> 8     for tweet in sntwitter.TwitterSearchScraper(quer).get_items():
      9         if len(tweets)==limit:
     10             break

File ~\anaconda3\lib\site-packages\snscrape\modules\twitter.py:680, in TwitterSearchScraper.get_items(self)
    677 	del params['tweet_search_mode']
    678 	del paginationParams['tweet_search_mode']
--> 680 for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
    681 	yield from self._instructions_to_tweets(obj)

File ~\anaconda3\lib\site-packages\snscrape\modules\twitter.py:369, in _TwitterAPIScraper._iter_api_data(self, endpoint, params, paginationParams, cursor, direction)
    367 while True:
    368 	_logger.info(f'Retrieving scroll page {cursor}')
--> 369 	obj = self._get_api_data(endpoint, reqParams)
    370 	yield obj
    372 	# No data format test, just a hard and loud crash if anything's wrong :-)

File ~\anaconda3\lib\site-packages\snscrape\modules\twitter.py:339, in _TwitterAPIScraper._get_api_data(self, endpoint, params)
    337 def _get_api_data(self, endpoint, params):
    338 	self._ensure_guest_token()
--> 339 	r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
    340 	try:
    341 		obj = r.json()

File ~\anaconda3\lib\site-packages\snscrape\base.py:216, in Scraper._get(self, *args, **kwargs)
    215 def _get(self, *args, **kwargs):
--> 216 	return self._request('GET', *args, **kwargs)

File ~\anaconda3\lib\site-packages\snscrape\base.py:212, in Scraper._request(self, method, url, params, data, headers, timeout, responseOkCallback, allowRedirects)
    210 	msg = f'{self._retries + 1} requests to {req.url} failed, giving up.'
    211 	logger.fatal(msg)
--> 212 	raise ScraperException(msg)
    213 raise RuntimeError('Reached unreachable code')

ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3Anarendramodi%29+until%3A2014-05-13+since%3A2013-11-01&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.

**Comment by EKANSHironfist** [comment]
yesterday snscrape was running fine , but encountered this error today?

**Comment by EKANSHironfist** [comment]
attached above is the Error msg and error flow
