### ISSUE TITLE
(Twitter) ValueError: missing media

### ISSUE THREAD

**Issue by oklebs** [JustAnotherArchivist/snscrape#532]
Hello, I am using the sntwitter module and for a specific query, I get a ValueError: missing media. The generator seems to stop once this error is raised and there is no way to continue the generator. However, this query worked yesterday and currently still works on other queries like '(clean energy) OR (#cleanenergy)' right now.

My code is as follows:

```
tweets_list_ge_eu = []

max_tweets = 5000
search_text = '(green energy) OR (#greenenergy)'
tweets_since = '2021-06-01'
tweets_until = '2022-06-01'
lang = 'en'
loc_near = 'Europe'

for i,tweet in enumerate(sntwitter.TwitterSearchScraper('{0} since:{1} until:{2} lang:{3} near:{4}'.format(search_text, tweets_since, tweets_until, lang, loc_near)).get_items()):
    if i > max_tweets:
        break
    tweets_list_ge_eu.append([tweet.date, tweet.rawContent, tweet.hashtags, tweet.lang, tweet.user.location, tweet.coordinates, tweet.place])
    
tweets_df_ge_eu = pd.DataFrame(tweets_list_ge_eu, columns=['date_time', 'original_content', 'hashtags', 'language', 'user_location', 'coord', 'place'])
tweets_df_ge_eu
```

May I know how to get past this error? Thanks a lot in advance.

**Comment by TheTechRobo** [comment]
I can reproduce with `snscrape --version` being `snscrape 0.4.3.20220107.dev56+gd72b519`. Here are my locals:

https://transfer.archivete.am/inline/JCTL6/snscrape_locals_npcmxe25

I used this command:

`snscrape --dump-locals --progress twitter-search "(green energy) OR (#greenenergy) since:2021-06-01 until:2022-06-01 lang:en near:Europe"`

In all other cases it's been a transient error, so I suggest trying again in a few hours.

**Comment by JustAnotherArchivist** [comment]
→ #470
