### ISSUE TITLE
[fix]: Output valid JSON with the `--jsonl` flag

### ISSUE THREAD

**Issue by T145** [JustAnotherArchivist/snscrape#538]
Presently this program only outputs individual JSON objects when handling an action with the `--jsonl` flag included.

Would it not be better to wait and output a valid JSON object array?

**Comment by TheTechRobo** [comment]
That's what JSONL is -- JSON Lines, aka one valid object per line.

It's a lot better for this IMO, considering that to output an entire array would mean storing all the objects in RAM until it's finished.

It also can be significantly faster to parse JSONL if you know which line(s) your object is on, rather than parsing the whole array.
