### ISSUE TITLE
NSFW tweets missing

### ISSUE THREAD

**Issue by Twi-Hard** [JustAnotherArchivist/snscrape#542]
Until recently snscrape was getting the nsfw tweets (at least from what I tested). Now they don't come up at all even if I specify the tweet ID. So I went and tested it on [twarc2](https://twarc-project.readthedocs.io/en/latest/twarc2_en_us/) and it was able to get them. I know it's using a different API but is there a way to include those tweets in snscrape?
I was using both snscrape and twarc2 in my script (shell script.. I don't know how to code any other way) because they gave different metadata.
Here's the url twarc2 uses to fetch data.. I don't know if it's relevant or not.
```
https://api.twitter.com/2/users/1181533597993439233/tweets?expansions=author_id%2Cin_reply_to_user_id%2Creferenced_tweets.id%2Creferenced_tweets.id.author_id%2Centities.mentions.username%2Cattachments.poll_ids%2Cattachments.media_keys%2Cgeo.place_id&tweet.fields=attachments%2Cauthor_id%2Ccontext_annotations%2Cconversation_id%2Ccreated_at%2Centities%2Cgeo%2Cid%2Cin_reply_to_user_id%2Clang%2Cpublic_metrics%2Ctext%2Cpossibly_sensitive%2Creferenced_tweets%2Creply_settings%2Csource%2Cwithheld&user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld&media.fields=alt_text%2Cduration_ms%2Cheight%2Cmedia_key%2Cpreview_image_url%2Ctype%2Curl%2Cwidth%2Cpublic_metrics&poll.fields=duration_minutes%2Cend_datetime%2Cid%2Coptions%2Cvoting_status&place.fields=contained_within%2Ccountry%2Ccountry_code%2Cfull_name%2Cgeo%2Cid%2Cname%2Cplace_type&max_results=100&pagination_token=7140dibdnow9c7btw3w4seexuxnrx5hdt4s9zc5s2dlis
```
This is the twitter I use to test this since it's small and has both SFW and NSFW stuff:
https://twitter.com/DoshNSFW
snscrape used to get most of the images, now it gets none.
It wasn't just that account I was able to get nsfw tweets from in the past.. most accounts I tried worked.
I can't get all of the tweet IDs for larger accounts without snscrape so right now I can't do much.

snscrape got 42 tweets with `twitter-user` and `twitter-profile` combined. Twarc2 gets all 195 tweets with `twarc2 timeline doshnsfw` 164 of those tweets contain the metadata `"possibly_sensitive": true`

I don't have access to my old files I used for testing so I don't know exactly how many tweets snscrape was able to get before.

**Comment by JustAnotherArchivist** [comment]
Those are age-restricted tweets, something Twitter introduced early this year. snscrape cannot currently grab them: #419

When that is implemented, it most likely still won't work with `twitter-user` since that uses the search (it's just a shorthand for `twitter-search 'from:username'`), and I believe such tweets are impossible to find via the search. But it can probably be made to work with `twitter-profile` in combination with #392. That will require a separate request for each age-gated tweet though, so it will be quite slow.

But good test case, and I hadn't really considered the integration into `twitter-profile` before, so thanks for that!
