### ISSUE TITLE
Twitter scraper failed, giving up (after 'Read timed out')

### ISSUE THREAD

**Issue by olesyamba** [JustAnotherArchivist/snscrape#596]
Hello! I try to scrape tweets using snscrape. I used dev version of package snscrape-0.4.3.20220107.dev65+g46a6030 because I need to scrape number of likes, replies, retweets too. Unfortunately, it causes the error: 

<img width="998" alt="Снимок экрана 2022-11-24 в 18 37 27" src="https://user-images.githubusercontent.com/118986574/203797637-4bd326d1-8825-4877-a80f-a8cc682c6a0d.png">

Can you help me please?:(((

**Comment by JustAnotherArchivist** [comment]
This is a network-related issue. Are you using some sort of proxy? Can you access Twitter otherwise from the same machine?

**Comment by jbellic** [comment]
I can confirm the issue - search doesn't work anymore (without proxy usage)

**Comment by JustAnotherArchivist** [comment]
Then you got your IP banned or have a network problem. Everything works perfectly fine for me from three continents.

**Comment by jbellic** [comment]
Even with a rotating proxy still the same issue...but opening the generated url in browser works fine (or doing advanced search manually)

**Comment by JustAnotherArchivist** [comment]
That's weird. Are browser and snscrape connecting to the same Twitter server IP? Or is there perhaps a strange IPv4/IPv6 thing going on? Or different DNS, e.g. enabled DNS-over-TLS in the browser vs system DNS for snscrape? Also, if you don't mind sharing, where in the world is the affected machine (country and ISP)? I'm ruling out a systematic thing on Twitter's side since everything works fine here from three completely unrelated networks on different continents and since there are few reports of this issue, but maybe there's a more localised issue on their side. Were you running a very large number of scrapes before this problem began?

**Comment by jbellic** [comment]
No large scrapes done so far (europe) and i'm not sure if the same Twitter server IP is used for both ways. The rotating proxy mainly uses IP addresses in the US. With the playwright framework I'm able to fetch tweets by doing traditional scraping via advanced search.

**Comment by TheTechRobo** [comment]
Does playwright still use the proxy?

**Comment by jbellic** [comment]
No proxy for playwright

**Comment by jbellic** [comment]
Seems like a networking issue (works on a different machine)...it's only strange that within the browser I don't have any issues.

**Comment by TheTechRobo** [comment]
Are you using snscrape and playwright in different environments (e.g. Docker, venv, etc)?

**Comment by jbellic** [comment]
No, I tested both in the same environment. Maybe twitter blocks by evaluating some combinational components (not only by IP).

**Comment by TheTechRobo** [comment]
Maybe they're doing TLS sniffing? i.e. checking for Python's SSL certificate store or something?

**Comment by JustAnotherArchivist** [comment]
What kind of ISP is that with? Residential, datacentre, cloud, ...?
