### ISSUE TITLE
Is there any possibility to extract tweet threads from the same username?

### ISSUE THREAD

**Issue by ssakinah** [JustAnotherArchivist/snscrape#600]
Hello there. 

Below is the code snippets where i scrape tweets related to a username. My project needs to combine tweets "from tweets" with it's reply. In simpler words, I want to get data of threads from the same username. Is that possible?

`for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:username').get_items()):`
`for i,tweet in enumerate(sntwitter.TwitterSearchScraper('@username').get_items()):`
`for i,tweet in enumerate(sntwitter.TwitterSearchScraper('username').get_items()):`
`for i,tweet in enumerate(sntwitter.TwitterSearchScraper('to:username').get_items()):`

**Comment by JustAnotherArchivist** [comment]
You could use a combined search query like `from:username OR to:username OR username`. (I believe that `@username` has the same effect as `username`, searching for the name in tweet texts rather than at-mentions.)
You'll have to combine them into threads via `conversationId` and `inReplyToTweetId` outside of snscrape though.

**Comment by ssakinah** [comment]
Thank you for your help. I'm still new and trying to figure things out. Can I get extra reading or resources about how to combine the threads?

**Comment by JustAnotherArchivist** [comment]
I don't think there are any. It's not something I have ever done. Basically, you'd need to group all tweets together by the `conversationId`, and then you could build a tree within each group using the `inReplyToTweetId`.
