### ISSUE TITLE
Reddit Scraper Broken - (PushShift.io) Parameter change for sort=desc to sort=created_utc

### ISSUE THREAD

**Issue by DanielAeon** [JustAnotherArchivist/snscrape#619]
Looks like Pushshift have change the "**sort**" parameter, which is also broken on www.redditsearch.io

By default it is sending "sort=desc" which seems to have been change to support 
permitted": [
"id",
"created_utc",
"score"
]

I believe this needs to be changed to  "**sort=created_utc**" now, or give the option to send one of the 3 new parameters

Eg:
https://api.pushshift.io/reddit/search/submission?q=dogs&size=100&sort=created_utc

**Comment by JustAnotherArchivist** [comment]
Thanks for the report. Looks like Pushshift is a bit unstable/unreliable at the moment in general and undergoing a migration according to posts in /r/pushshift. Someone also [mentioned the `sort` issue there](https://old.reddit.com/r/pushshift/comments/zhzaea/the_day_has_finally_arrived_pushshift_api_move/j08cbl0/). Let's wait a bit for the dust to settle rather than changing now and then again in a few days.

**Comment by peterjwms** [comment]
Is there any way to get around this on my own now? I'm doing a project for a class that's due in a couple days where I'm trying to scrape Reddit to expand my data from the 100+ sample comments I pulled a couple weeks ago to several thousand comments.

**Comment by JustAnotherArchivist** [comment]
Given how unreliable Pushshift is currently, I'd recommend using the Reddit API with PRAW for the time being if you can make your project work with that at all.

**Comment by peterjwms** [comment]
Okay, thanks, I'll see if I can get that to work.

**Comment by DanielAeon** [comment]
The easy solution would be just to make the parameter optional? than doesn't matter if it changes people can just change the query to match?

**Comment by JustAnotherArchivist** [comment]
No. snscrape produces reverse-chronological output for feed-like things since that's inherent to how almost all social networks make the data available (and often don't support anything else). So the sorting *shouldn't* be adjustable; snscrape just needs to do the correct thing internally. It would also break `--since` and (for Reddit specifically) the merging of submission and comment streams.
The issue here is that things went wrong while Pushshift was migrated to a different server, and now all kinds of stuff about the API has changed in undocumented and unreliable ways. At this point, it's unclear whether the current behaviour will stay, things will get reverted, or something else, but the work is clearly ongoing. So I'd rather wait a bit for things to stabilise. If that doesn't happen soonish, I'll revisit that position though.
