### ISSUE TITLE
TwitterSearchScraper error using multithreads-4 requests to https://api.twitter.com/1.1/guest/activate.json failed, giving up.

### ISSUE THREAD

**Issue by bojun1208** [JustAnotherArchivist/snscrape#622]
Hi, I am getting the following errors using multithreads with TwitterSearchScraper, I have around 10k handles, and each thread will take a care of part of handles and try to retrieve the tweets of users for the last 7 days. It seems like there is an ip ban, the amount of requests cannot exceed certain threshold like within 15mins from same ip.

code snippet:
![image](https://user-images.githubusercontent.com/88610417/209442237-669d3ad9-59a3-4e40-83bd-484d9ab414c3.png)
error: 
![image](https://user-images.githubusercontent.com/88610417/209442261-47ab9b4b-50a2-4c98-a42f-cff83b8a056b.png)

**Comment by JustAnotherArchivist** [comment]
snscrape is not thread-safe (cf. #307 and #584). Twitter strongly rate-limits the tokens, and there is no mechanism for sharing that between threads at the moment. If you can, use the CLI instead, which attempts to share tokens between processes and works pretty well for reasonable numbers of parallel processes (I've personally used up to 20 or so). You'll want to write JSONL output and then post-process that afterwards to extract the fields you actually need.

**Comment by bojun1208** [comment]
Hi, Thank you so much for the reply. I am currently using the rotating proxy against ip ban, control the scraping rate, store the handles with problems and later run a makeup method in the code to re-scrape, so far, I don see tweets scrapped under different handles messed-up in general, it seems work ok to solve majority of the problem. I have 2 more questions as follows:
1. Since you have mentioned about CLI using parallel processes, any example/tutorial I could refer to achieve what you have mentioned.
2. What is the fundamental logic/mechanism of the bear guest token used in snscrape, any past thread/discussion I could refer to?
Thank you for your time.

**Comment by JustAnotherArchivist** [comment]
The errors in this issue are exactly because of the lack of thread safety (or, more accurately, lack of sharing tokens between threads). So it clearly does not work fine. :-)

1. You will simply want to run `snscrape --jsonl twitter-user $username` in parallel, most likely redirecting the output to a separate file for each user. There are numerous ways to achieve that; popular choices on Unixoid systems include `xargs` and `parallel`, but you could do it in plain Bash if you wanted. I described one method in <https://github.com/JustAnotherArchivist/snscrape/issues/307#issuecomment-968636591>.
2. Those tokens are how Twitter's web interface works. They use them to authenticate accesses to the undocumented API. The browser keeps the token in a cookie. snscrape just emulates that. Thread safety was never a goal of snscrape, and so that implementation isn't thread-safe. Parallel processes are something that has been relevant ever since I first wrote the code, so that's supported. That's pretty much all there is to it.

**Comment by bojun1208** [comment]
Hi, thank you so much for the detailed explanations! :-) I am done with my question, I shall close it.
