### ISSUE TITLE
Unable to scrape tweets from certain months

### ISSUE THREAD

**Issue by daanvanderveen1** [JustAnotherArchivist/snscrape#674]
Hi!

I am using the TwitterSearchScraper to fetch the tweets of certain users over a 8 year time period.
It works fine for the most part, except for the months: February, April, June, September and November.

I am not sure what causes this error. Can anybody help me with this?

The code I am using is the following:

![Scherm­afbeelding 2023-01-14 om 20 48 05](https://user-images.githubusercontent.com/45860350/212493587-627939d9-b1bf-4ea5-96dd-ea99654e401e.png)

This is how it looks in the terminal for every user:

![Scherm­afbeelding 2023-01-14 om 20 49 45](https://user-images.githubusercontent.com/45860350/212493646-aa3f9436-7982-47d6-b444-0f5363a1e4d3.png)

**Comment by JustAnotherArchivist** [comment]
I think this is because you're passing invalid dates to `until`. There is no 2015-06-31, for example, since June only has 30 days.

You also don't want to pass the last day of a month to `until` but the first day of the next month. The `until` filter is exclusive, i.e. you get results made before that date but *not* on that date.

This does indeed work correctly: `snscrape twitter-search 'from:dogecointicker since:2015-06-01 until:2015-07-01'`

**Comment by daanvanderveen1** [comment]
@JustAnotherArchivist Yes this was indeed the issue. Thank you so much!!
