### ISSUE TITLE
Asyncio to improve the speed 

### ISSUE THREAD

**Issue by silkywork** [JustAnotherArchivist/snscrape#732]
Hello, 

Was curious to know if it would be possible to improve the speed of the scraping by using asyncio for scraping tweets?

As it seems that snscrape is I/O bound ... thought it might be a great idea. 

I have tried but it does not seem to improve to speed ... Before I dig further I just wanted to know if that is a viable option and would you have any recommandation on how to implement it? 

Thank you,

**Comment by JustAnotherArchivist** [comment]
The scraping is not parallelisable, so async I/O won't make a difference unless you run multiple scrapes at the same time, which is not supported (cf. #623). So no, not a viable option currently.

**Comment by srfonso** [comment]
Hello, I decided to choose the "threading" way. I am making a wrapper for this project with threads and storage pipelines and it works very well (of course, I recommend the use of proxies). And the problem of _"The scraping is not parallelisable"_ The idea is to "manually" split the queries (f.e you want to search tweets about "futbol"):
1. You can split the search by date range (using until: and since: twitter dorks).
2. Parallelize this using threads.

**Comment by TheTechRobo** [comment]
Make sure not to use the snscrape module inside a thread. Running it in multiple processes is fine, multiple threads is not. (#623)

**Comment by JustAnotherArchivist** [comment]
Threading is not supported, as I already linked above. Splitting queries like that only works for the Twitter search scraper and nothing else. And even for that one, it can't be integrated into snscrape because it'd have to buffer all the results from the older time windows to get the correct reverse-chronological order, which leads to silly memory usage. It's certainly something you can do externally though.

**Comment by srfonso** [comment]
Okey, thanks you very much for your support (and congratulations for this excellent project). 

However I have question, (if I have not skipped relevant information) the main problem of threading using snscrape as lib (and not the CLI in different processes) is that the GuestTokenManager is not thread-safe, different threads will not share this token and it will lead in a Twitter block because Twitter strongly rate-limits the tokens. But, if we use rotating proxies Twitter will have more difficulties to detect this issue, or am I totally wrong?

I just make a test, with a dataset of 400K tweetID, proxies and 50 concurrent threads during 20 minutes (using the TwitterTweetScraper) and it worked fine. But I don't know if I'm missing something important.

Thanks you for your time and for sharing to us this repo.

**Comment by JustAnotherArchivist** [comment]
This issue is about asyncio, not threading. You're on your own if you want to use threading until official support for that might be implemented in the future. It could work, or it could blow up in exciting ways (or in C terminology: undefined behaviour). My only advice about it for the time being is: don't.

**Comment by codilau** [comment]
Hello, snscrape is priceless for my use case. I'm studying this section now because i'n still unsure i'm using it correctly. I'm not sure if this should or should not work but in my case it does. I'm simulating the deprecated twitter V1 Stream in order to integrate easily into my existing code. so right now I'm testing continous paralel scrapes using asyncio tasks running on a secondary Process in the main app.

the code spawns tasks according to queries constructed to be of a set maximum char count, so the number of tasks varies according to the number of followed accounts. I'm running 120 paralel tasks that periodically ask for the newest tweets at dynamic intervals according to how busy a certain stream is, next a callback dumps the new tweets into a shared queue. I can tell you it runs flawlessly.

**Comment by JustAnotherArchivist** [comment]
@codilau snscrape has no async parts, and threading is not supported. If it 'runs flawlessly', you might be getting lucky or missing the issues. As with all race conditions, they only bite occasionally.
The questions are off-topic on this issue and have already pretty much been answered in other issues. See e.g. #211 and #475.
