### ISSUE TITLE
scrape userprofile get only tweets of last year 

### ISSUE THREAD

**Issue by Nader-Khalil-IDSC** [JustAnotherArchivist/snscrape#741]
### Describe the bug

Hello I'm using the basic example to do user profile scrapping but it only give me few tweets knowing that I know there are much more at this account 
The Code : 

![image](https://user-images.githubusercontent.com/121941112/221593863-48428878-42cb-4ec1-8b0f-c6f7e6a8eb11.png)

### How to reproduce

Don't know a solution I tried to specify a time frame range to scrape tweets in between nothing showed up 

### Expected behaviour

Expected to have more tweets than this it should be in thousands 

### Operating system

Google Colab Notebook

### Python version: output of `python3 --version`

Python 3.8.1

### snscrape version: output of `snscrape --version`

snscrape 0. 5.0.2023011 3

### Scraper

twitter-user

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
This is another case of #4. The [oldest tweet that's returned](https://twitter.com/TrueIndology/status/1609227129186844675) mentions that the account had been suspended for years, and I suspect they never reindexed the older tweets after the reinstatement.

You can try the profile scraper instead of the search, but that's limited to about 3200 results, nowhere near the account's almost 21k statuses. I don't know of a way to find the rest directly.
