### ISSUE TITLE
snscrape.base:Error retrieving 

### ISSUE THREAD

**Issue by ShayanHodai** [JustAnotherArchivist/snscrape#763]
### Describe the bug

When I run the provided code below, I get ERROR:snscrape.base:Error retrieving with a link which is, This site can’t be reached The webpage at https://api.twitter.com/

It was working perfectly fine few hours ago, It seems snscrape can't scrape tweets anymore due to changes in twitter API policies

### How to reproduce
```python3
accounts = ['BarackObama'] #accounts which we want to scrape tweets from
tweets = []
for account in accounts:
    for limit, tweet in enumerate(sntwitter.TwitterSearchScraper('from:{0} since:2023-2-01 min_replies:20 -filter:replies'.format(account)).get_items()):  #scrape tweets and quote tweets since the given date which are not replies to other tweets and have at least 20 replies
        if limit >= 500:  #maximum number of tweets. 500 tweets from each account
            break
        tweets.append([tweet.id, tweet.date, tweet.username, tweet.content])  #the features we want from tweets

tweets_df = pd.DataFrame(tweets, columns=['Id', 'Date', 'Username', 'Tweet']) #creating tweets dataframe
```

### Expected behaviour

create the tweets_df

### Operating system

Ubuntu 20.04

### Python version: output of `python3 --version`

Python 3.8.10

### snscrape version: output of `snscrape --version`

snscrape 0.6.0.20230303

### Scraper

twitter-user

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

**Comment by shivendra-algo** [comment]
I am also having the same issue....suddenly the code stopped working

Gave me this error-
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=%28%22Bajaj+Auto%22+OR+%22Bajaj_Auto%22%29+lang%3Aen+since%3A2023-03-14+-filter%3Aretweets&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.

**Comment by JustAnotherArchivist** [comment]
#760

**Comment by ShayanHodai** [comment]
snscrape has released an update on 14th of March. version 0.6.1.20230314
1. first update pip: pip install --upgrade pip
2. then update snscrape to the latest version: pip install --upgrade snscrape 
3. check the snscrape's version to be 0.6.1.20230314: pip list | grep snscrape 
4. start using snscrape again
