### ISSUE TITLE
Add string ID properties for values exceeding IEEE-754 precision limits

### ISSUE THREAD

**Issue by alexanderolvera** [JustAnotherArchivist/snscrape#794]
### Describe the feature

Since Twitter is already sending us this data, I figured it would be an easy change to implement. 

This is for non 64bit systems/languages or languages that use the [IEEE-754](http://en.wikipedia.org/wiki/IEEE_754-2008) double-precision (looking at you Javascript) that might ingest this scrapers data.

This issue is outlined in twitters documentation here. https://developer.twitter.com/en/docs/twitter-ids

### Would this fix a problem you're experiencing? If so, specify.

This would resolve an issue on my end where we are using SNScrape in a python api but systems ingesting the api are using Nodejs.

### Did you consider other alternatives?

Alternatives would be to apply a transformation on our end (Which we have already done). I figured since Twitter is already sending the data, it probably won't be too much trouble to tack on the extra properties where available.

**Comment by JustAnotherArchivist** [comment]
This is actually something I considered when I wrote the code originally. Because Python has arbitrary integers, I deliberately didn't include strings which are awkward to work with and converted the strings returned from Twitter to integers where necessary (because Twitter is inconsistent in what it returns sometimes). The IDs are decimal and numeric, so they should be a number type.

This predates JSON output in snscrape. However, I think the same is still true. JSON supports arbitrary numbers, and if a parser does not handle that, i.e. either parses it accurately or raises an error that it cannot correctly process the value, I consider that a bug in that parser, not in the JSON data. I'm not a fan of adding poor workarounds for buggy downstream software.

*If* you were to convince me that this should be added, I'd want a more general solution than just something specific to certain fields on Twitter. The same issue is potentially also present in other modules. Mastodon uses similar IDs for toots, for example. I'd also want it to be opt-in, e.g. via an optional argument to the `.json()` method.

**Comment by alexanderolvera** [comment]
> This is actually something I considered when I wrote the code originally. Because Python has arbitrary integers, I deliberately didn't include strings which are awkward to work with and converted the strings returned from Twitter to integers where necessary (because Twitter is inconsistent in what it returns sometimes). The IDs are decimal and numeric, so they should be a number type.
> 
> This predates JSON output in snscrape. However, I think the same is still true. JSON supports arbitrary numbers, and if a parser does not handle that, i.e. either parses it accurately or raises an error that it cannot correctly process the value, I consider that a bug in that parser, not in the JSON data. I'm not a fan of adding poor workarounds for buggy downstream software.
> 
> _If_ you were to convince me that this should be added, I'd want a more general solution than just something specific to certain fields on Twitter. The same issue is potentially also present in other modules. Mastodon uses similar IDs for toots, for example. I'd also want it to be opt-in, e.g. via an optional argument to the `.json()` method.

My argument would be that, the data is already available. Twitter even identified it has a common issue in downstream web software and made their change to accommodate them. It costs this tool almost no computational power to include it and I also doubt it would be considered a breaking change for anyone using the tool currently as it only adds a new properties.

If thats not enough of a reason, I understand. I can close the PR/issue and will continue to use the tool from my fork instead.

**Comment by JustAnotherArchivist** [comment]
> Twitter even identified it has a common issue in downstream web software and made their change to accommodate them.

Which, I think, is exactly (part of) the reason why JS's `JSON.parse` *still* hasn't been fixed. If everyone can just add extra data to all their objects, why bother fixing the underlying bug? There is apparently some movement to finally add `BigInt` support though; maybe it'll even happen this decade...
Naturally, Twitter's API was and is also used heavily by its own web app. So their workaround for JS was very much driven by that; it was the only way they could make the web app work at all.

I'm not opposed to adding a compatibility mode in the way I described above, since yeah, it is a real problem for people who have to use such buggy parsers. I just don't want to have to think about it at all in the future as snscrape evolves (e.g. adding new fields), so it should be implemented generically. I'm open to other suggestions how that could be done. Adding fields specifically to the objects returned by the Twitter scraper is not the way forward though, in my eyes.
