### ISSUE TITLE
Any way to limit the number of returned results, but also resume?

### ISSUE THREAD

**Issue by IvanTrendafilov** [JustAnotherArchivist/snscrape#80]
For example, I'd like to fetch 40 tweets or so for a particular search term and grab the cursor. Then, I'd like to be able to resume and fetch the next 40 tweets from the same search?

**Comment by JustAnotherArchivist** [comment]
Well, the cursors are opaque strings returned by Twitter, and constructing them to resume from an arbitrary point in the results is not feasible. It could be done in principle at the page level but is not currently implemented. The `--cursor` option mostly exists to manually recover from crashes, in which case you can get the cursor from the crash dump file. It is not intended that the user interacts with the pagination otherwise; that is all supposed to be fully transparent in the background.

What you could do is use the `max_id` filter on Twitter's search. For example, `snscrape --max-results 40 twitter-search foo`. Later, run `snscrape --max-results 40 twitter-search 'foo max_id:X'` where `X` is the tweet ID of the last result from the previous run minus one. However, I cannot recommend this method unless you do blocks on the order of 10k results rather than 40; it will be very inefficient otherwise and may well get your IP banned due to the frequent guest token requests.

Depending on what you're trying to do exactly, you may be able to use the (undocumented) API. The `Scraper.get_items` iterator handles the pagination and cursor transparently, and at least in principle, it should be possible to block at any time and then just continue to iterate over it later. If your delays between pagination requests become very large, this might break though. Example:

```python
import snscrape.modules.twitter
for tweet in snscrape.modules.twitter.TwitterSearchScraper('foo').get_items():
	# Do something with tweet
	if someCondition:
		time.sleep(60) # Resume processing after 60 seconds
```

**Comment by IvanTrendafilov** [comment]
Thanks! I ended up using `--max-results` and then grabbing the `id` of the last tweet and then updating the query to use `max_id` parameter  and it worked great.
