### ISSUE TITLE
Proxy service that works on twitter

### ISSUE THREAD

**Issue by giakoumis** [JustAnotherArchivist/snscrape#801]
I am trying to use TwitterSearchScraper with proxies but I am getting blocked. 
I have tried a few different services but to no avail. Does anyone here been able to use a proxy successfully and if yes can you share the service you are using?

**Comment by DrSocket** [comment]
hi @giakoumis @JustAnotherArchivist , where would be the right place to discuss about proxy? I've also not been able to get it to work. currently adding a proxies dict above self._session.merge_environment_settings(... proxies... ) but getting blocked as well. can't find any info online, the longest discussion on this topic anywhere online is: https://github.com/JustAnotherArchivist/snscrape/issues/74 where someone seems to have gotten it to work but did not answer anyone and now the issue is closed.

**Comment by JustAnotherArchivist** [comment]
This is an issue tracker for snscrape development. Reports and discussion about problems with proxy *support* (as in, snscrape being able to use proxies) can happen in issues here. Discussion about which proxies work with which service can happen anywhere that isn't here; it's out of scope.
