### ISSUE TITLE
Support for --until

### ISSUE THREAD

**Issue by ppival** [JustAnotherArchivist/snscrape#81]
Another tool I have used, GetOldTweets3, supports not only the `--since` DATE flag, but also `--until` DATE, allowing a twitter scrape to focus between two dates. Syntax simply looks like `--since 2015-05-24 --until 2015-08-23`

Would it be possible to enable this for snscrape?

**Comment by JustAnotherArchivist** [comment]
It could be implemented, but it wouldn't really gain anything. `--since` is scraper-independent; the way it works is that it exits when reaching a result before the specified date, preventing paginating through potentially many older results and shortening the scrape. If I were to add `--until`, it would merely suppress the output of items newer than some date, but in the background, it would still have to fetch all results newer than that as well. So you don't gain any time or resources.

However, for Twitter specifically, you can use Twitter's proper `since` and `until` search filters. For example, `snscrape twitter-search 'foobar since:2019-01-01 until:2020-01-01'` would return tweets containing 'foobar' from the year 2019. `since:YYYY-MM-DD` produces tweets that were posted on that date or later; `until:YYYY-MM-DD` produces tweets that were posted before (but not on!) that date. (This used to be documented on the Twitter website, but they removed that since. You can find some more [here](https://web.archive.org/web/20200101004622if_/https://twitter.com/search-home) by clicking on 'operators' below the search field. That list was also incomplete though.)

**Comment by Tachevaz** [comment]
Thank you for this great tool, it's a savior!

About the "since" argument - is there a way to implement it in a script as well, as an argument to snscrape.modules.twitter.TwitterUserScraper()? Or can should it be added as a condition after snscrape.modules.twitter.TwitterUserScraper() has finished running?

**Comment by JustAnotherArchivist** [comment]
There are two ways to do that (without wasting time scraping things you're not actually interested in):

1. You can check the date of the `Tweet` objects returned by the scraper and break the loop when it's older than the time you're interested in. This is exactly what `--since` in the CLI does.
2. The user scraper is actually just a fancy wrapper around the much more general search scraper. So you could use that instead and rely on Twitter's date filters: `snscrape.modules.twitter.TwitterSearchScraper('from:username since:2020-01-01')`

**Comment by Tachevaz** [comment]
It worked, thank you so much!:))

**Comment by JustAnotherArchivist** [comment]
Closing this; see my first comment for the rationale.

**Comment by ppival** [comment]
Any reason this works for `twitter-search`, but not for `twitter-user`? The following just appears to sit there forever:
` snscrape twitter-user "barackobama since:2015-09-10 until:2015-09-12” > baracktweets.txt`

TIA! You, @JustAnotherArchivist, are just about the most patient and responsive maintainer I've ever come across! :-)

> It could be implemented, but it wouldn't really gain anything. `--since` is scraper-independent; the way it works is that it exits when reaching a result before the specified date, preventing paginating through potentially many older results and shortening the scrape. If I were to add `--until`, it would merely suppress the output of items newer than some date, but in the background, it would still have to fetch all results newer than that as well. So you don't gain any time or resources.
> 
> However, for Twitter specifically, you can use Twitter's proper `since` and `until` search filters. For example, `snscrape twitter-search 'foobar since:2019-01-01 until:2020-01-01'` would return tweets containing 'foobar' from the year 2019. `since:YYYY-MM-DD` produces tweets that were posted on that date or later; `until:YYYY-MM-DD` produces tweets that were posted before (but not on!) that date. (This used to be documented on the Twitter website, but they removed that since. You can find some more [here](https://web.archive.org/web/20200101004622if_/https://twitter.com/search-home) by clicking on 'operators' below the search field. That list was also incomplete though.)

**Comment by JustAnotherArchivist** [comment]
`twitter-user` is actually just a wrapper around `twitter-search` using the search term `from:username` (plus code to extract user information from the profile page). So: `snscrape twitter-search 'from:barackobama since:2015-09-10 until:2015-09-12'`

Happy to help! I'm glad this work is finally getting some use outside of the immediate use case I wrote it for. :-)

**Comment by Uzair1947** [comment]
can we give time to until and since

**Comment by JustAnotherArchivist** [comment]
@Uzair1947 #259

**Comment by ihabpalamino** [comment]
@JustAnotherArchivist i have a question for from:barackobama since:2015-09-10 until:2015-09-12 how can i write dates in a dynamic way by an input instead of writing it like that?

**Comment by JustAnotherArchivist** [comment]
@ihabpalamino You can use string formatting, but that's a general Python question and off-topic for here.
