### ISSUE TITLE
Can't understand 404 error

### ISSUE THREAD

**Issue by Mr-Freewan** [JustAnotherArchivist/snscrape#813]
Hi! I have a question and I can't understand one thing:

"using the latest version of snscrape" is **OK**
"you are not using a proxy or VPN" is **OK**
"you are not using a cloud computing provider such as AWS or GCP" is **OK**
"you can run the same search query successfully in a browser" - can't check, because use server without GUI.

I am using twitter profile scraper as a python library. It has not been working since yesterday (~19 GMT) and gives a 404 error. The service provider is not Amazon or Google.

But, when I use it exactly the same way on my home computer, which is connected to the same ubuntu server via VPN tonnel, it works fine. It turns out the same IP.

What could it be?

Error:
https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3ABVB&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
CRITICAL:snscrape.base:Errors: blocked (404)

**Comment by Mr-Freewan** [comment]
> If your home computer uses the same IP, you can check with a browser from your computer. But please double-check that the connections really go through your server. `python3 -c 'import requests; print(requests.get("https://wtfismyip.com/text").text)'` is a reasonable way to check that (and open the same URL in a browser, too). Just to exclude any VPN config errors.
> 
> If that all checks out, I'd like to see the debug logs of `snscrape -n 1 -vv twitter-user textfiles` from both machines.

Logs:

[home_plus_vpn.txt](https://github.com/JustAnotherArchivist/snscrape/files/11113503/home_plus_vpn.txt)
[server.txt](https://github.com/JustAnotherArchivist/snscrape/files/11113504/server.txt)

**Comment by Mr-Freewan** [comment]
> You're not using the latest snscrape version on the server.

Sorry. My mistake. Just one second. This log outside venv)

**Comment by Mr-Freewan** [comment]
> You're not using the latest snscrape version on the server.

right log
[server.txt](https://github.com/JustAnotherArchivist/snscrape/files/11113574/server.txt)

**Comment by Mr-Freewan** [comment]
I can try to get the log from another server with a different IP address and location. I tried to test run a script on it, but it also does not work and gives the same error.

**Comment by JustAnotherArchivist** [comment]
Your server connects to a weird IP for api.twitter.com:

```
2023-03-30 19:02:26.006  DEBUG  urllib3.connectionpool  Starting new HTTPS connection (1): api.twitter.com:443
2023-03-30 19:02:26.191  DEBUG  snscrape.base  Connected to: ('54.240.186.247', 443)
```

I'm pretty sure that's not an IP Twitter has ever used. It certainly isn't what api.twitter.com resolves to currently based on my tests on various machines around the globe (104.244.42.2, 104.244.42.66, 104.244.42.130, 104.244.42.194).

**Comment by Mr-Freewan** [comment]
This server in Netherlands.
Same servers in Netherlands and Germany connects to '104.244.42.2', 443 and '104.244.42.65', 443, but didn't work too.

**Comment by JustAnotherArchivist** [comment]
Complete debug log where it connects to the right IPs please. I checked from a server in NL, and it got the correct IP. It'd be weird anyway if they did geofencing at the DNS level.

**Comment by Mr-Freewan** [comment]
[serv2.txt](https://github.com/JustAnotherArchivist/snscrape/files/11114245/serv2.txt) Germany
[serv3.txt](https://github.com/JustAnotherArchivist/snscrape/files/11114246/serv3.txt) Netherlands

**Comment by Mr-Freewan** [comment]
[serv4.txt](https://github.com/JustAnotherArchivist/snscrape/files/11114271/serv4.txt) same server, which serv3.txt log

**Comment by JustAnotherArchivist** [comment]
serv3.txt and serv4.txt still use a wrong IP.
serv2.txt is more interesting. I don't see anything odd in that log. What does it look like from your home connection when using that server as a VPN or other transparent proxy?

**Comment by Mr-Freewan** [comment]
> serv3.txt and serv4.txt still use a wrong IP. serv2.txt is more interesting. I don't see anything odd in that log. 

And how can i solve this problem with wrong IP? =)

> What does it look like from your home connection when using that server as a VPN or other transparent proxy?

It trying to connect ('104.244.42.129', 443) or ('104.244.42.193', 443). At browser it works normally

my head is spinning...

**Comment by JustAnotherArchivist** [comment]
> And how can i solve this problem with wrong IP? =)

I don't know. I have no idea how you even get those IPs. Maybe you're using a weird DNS server there, or the ISP is doing something strange.

> It trying to connect ('104.244.42.129', 443) or ('104.244.42.193', 443).

.129 and .193 are IPs of twitter.com, not api.twitter.com.

**Comment by Mr-Freewan** [comment]
> I don't know. I have no idea how you even get those IPs. Maybe you're using a weird DNS server there, or the ISP is doing something strange.

Netherlands and Germany are different providers =)

**Comment by JustAnotherArchivist** [comment]
Well yes, and the servers behave differently. Again, debug log when proxying through the German server please.

**Comment by JustAnotherArchivist** [comment]
Well there you go, so the German server's IP is just banned most likely. And the Dutch one has some sort of broken DNS.

**Comment by Mr-Freewan** [comment]
Very strange, because German server never used for bot

**Comment by ratroot92** [comment]
Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3Amaliksblr92+love+OR+love1+OR+home+OR+rizwan+since%3A2022-03-30&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe: blocked (404)
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3Amaliksblr92+love+OR+love1+OR+home+OR+rizwan+since%3A2022-03-30&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
Errors: blocked (404), blocked (404), blocked (404), blocked (404)

**Comment by ratroot92** [comment]
@JustAnotherArchivist was working two days ago

**Comment by JustAnotherArchivist** [comment]
@ratroot92 #783

**Comment by ratroot92** [comment]
today  i had to handover the project on Upwork and it is not working now

**Comment by JustAnotherArchivist** [comment]
@ratroot92 File a complete (separate) bug report, as mentioned in that issue.

**Comment by Mr-Freewan** [comment]
> Twitter's IP blocking is mysterious.
Yes...
> I'll consider this resolved then.
Ok...

**Comment by ratroot92** [comment]
![Screenshot from 2023-03-30 23-04-22](https://user-images.githubusercontent.com/49342301/228926474-7f66d3db-9985-4157-80d4-28c038e9fe6f.png)

**Comment by ratroot92** [comment]
![Screenshot from 2023-03-30 23-03-48](https://user-images.githubusercontent.com/49342301/228926539-da2ff74b-0a3c-44cd-b30b-d28874d19ef0.png)

**Comment by Mr-Freewan** [comment]
@JustAnotherArchivist I tried changing the DNS settings and it worked ¯\_(ツ)_/¯

Thank you for your help
