### ISSUE TITLE
What is the fastest and best way to scrape a list of tweet urls?

### ISSUE THREAD

**Issue by Wouze** [JustAnotherArchivist/snscrape#858]
Hello! 
Currently I'm getting so much tweet ids using nitter, and I want to scrape their public metrics using snscrape because tweet object here is so richful.

currently, I get Ids in batches, around 10 at a time
and I process them using pools.

```python
with ThreadPool(processes=len(urls)) as pool:
    for result in pool.imap(get_res, urls):
        for i in result:
            extracted_tweets.append(i)
``` 

with get_res() function.
```python
def get_res(url):
    return sns.TwitterTweetScraper(url).get_items()
``` 

so basically the unthreaded one will be (easy to read and understand):
```python
for tweet_url in urls:
    for i in sntwitter.TwitterTweetScraper(tweet_url).get_items():
        extract_tweets.append(i)
``` 

each tweet_url takes more than half a second, that's why I want faster way.

is the multi-threading way the right way?
is there is a better way?

Thanks

**Comment by JustAnotherArchivist** [comment]
Multithreading is not supported: #623

Twitter offers no way of fetching multiple tweets at once, so no, there is no more efficient way than parallelising. Due to the lack of multithreading support, you'll want to use separate processes.

Also, just in case, you say `tweet_url`, but the scraper takes tweet IDs, not URLs.

**Comment by Wouze** [comment]
Thanks

Yes `tweet_url` is misleading, sorry for that.
