### ISSUE TITLE
Duplicate Entries Returned

### ISSUE THREAD

**Issue by AnthonyFJGarner** [JustAnotherArchivist/snscrape#89]
The following code, executed in Jupyter Lab, produces a duplicate of each tweet. I can of course delete the duplicates but am puzzled as to what I might be doing wrong.

```
tweets=snscrape.modules.twitter.TwitterSearchScraper(query ='$CBAT since:2020-09-01')
for i in tweets.get_items():
date.append(i.date)
username.append(i.username)
content.append(i.content)
tcooutlinks.append(i.tcooutlinks)

df = (pd.DataFrame({'Date':date,'Username':username,'Content':content, 'Tcooutlinks':tcooutlinks}) )
```

**Comment by JustAnotherArchivist** [comment]
The code looks fine (apart from the lost indentation). I cannot reproduce this with Python 3.8.2 and the current snscrape code, and I've never seen duplicates before. This sounds like an issue with your environment instead. Or can you reproduce it with `snscrape twitter-search '$CBAT since:2020-09-01'` (also works fine here)?

**Comment by AnthonyFJGarner** [comment]
A foolish error on my part. Issue closed and sorry to have bothered you. What excellent software and thank you!

**Comment by JustAnotherArchivist** [comment]
No problem, thanks!

**Comment by ihahawen** [comment]
thanks，i use this`pd.DataFrame.from_records({'Date': date, 'Username': username, 'Content': content}).to_csv('text_files_test_20.csv',encoding='utf-8')` save to csv Customize my needs
