### ISSUE TITLE
Is it possible to configure verify=False

### ISSUE THREAD

**Issue by chrisgoddard** [JustAnotherArchivist/snscrape#934]
Is it possible to set the session/environment to verify=false? Many proxy apis don't seem to handle SSL correctly and skipping verification would solve this issue (tested locally)

**Comment by TheTechRobo** [comment]
I always just set the `CURL_CA_BUNDLE` environment variable to an empty string, which disables cert verification. Though I'd really suggest adding the proxy's certificate chain as trusted rather than disabling SSL entirely.

**Comment by chrisgoddard** [comment]
Excuse the dumb question but in the case where the proxy doesn't provide an https endpoint (I'm currently testing with scrape.do which just has a http/port 80 proxy), am I right in assuming there wouldn't be a cert chain?

**Comment by JustAnotherArchivist** [comment]
HTTP proxies (tunnels) work via the CONNECT verb. That is, they are establishing a TCP connection and then let the client (i.e. you) talk with the remote server (i.e. Twitter) normally, i.e. if connecting to an HTTPS server, the next step would be a (tunneled) TLS handshake. In that case, you still get a valid certificate just like if you connect directly.

Certificate validation only comes into play when you use an HTTPS proxy which itself has an invalid certificate (e.g. because it runs on a plain IP rather than a domain, since you can't get valid certificates for those). Under the hood, it still works the same though (HTTPS is just HTTP on top of TLS, after all): you establish a connection to the proxy server, then use CONNECT to get a connection through the proxy to the remote server, and then you do another TLS handshake with the remote server.

The protocol for the target server is independent from the protocol for the proxy server. You can use an HTTP proxy in the `HTTPS_PROXY` environment variable or an HTTPS proxy in `http_proxy`.

**Comment by chrisgoddard** [comment]
Thanks for the great explanation!

**Comment by TheTechRobo** [comment]
To add to this, in my experience, this issue is usually caused by the proxy stripping or otherwise invalidating the SSL connection. In this case, it might not return Twitter's certificate; it might return a self-signed one (i.e. untrusted by most computers). This is common especially for MITM proxies (proxies that let you read or change the data being set; an example is https://github.com/InternetArchive/warcprox, which needs to read the data that it's passing on). Based on [the documentation](https://scrape.do/documentation/) (click "python", then "Proxy Mode", then look at the example), this is indeed what is happening (the code says `# Disable warnings for self-signed certificate`). My guess is it's so that a request only counts toward your usage if it was successful, as they do mention that on their homepage.

I don't see them providing a certificate chain that you can mark as trusted, though. Their documentation just tells you to disable SSL verification...

It shouldn't matter too much since there's no authentication here but if you are worried, I'd contact them.
