### ISSUE TITLE
How to scrape less information per tweet using twitter-hashtag

### ISSUE THREAD

**Issue by AyoubBakkoury** [JustAnotherArchivist/snscrape#95]
Hi, 
I am trying to figure out which part of your very clear python script I should change if I want to get fewer information when scraping data. I'd like to get only the user_id, the date of the tweet and the localisation, and not the other information. Which would make the extracted file way much lighter, considering the amount of data I want to extract.

**Comment by JustAnotherArchivist** [comment]
(I'm not entirely sure what you mean by 'localisation'; could be either the inferred language of the tweet or the tweeter's location. I use the former below, but switching that is trivial of course.)

There are two ways how you can do that:

1. Use `--format`. For example, `--format '{user.id} {date} {lang}'`. For these fields, that should be safe. If you were to include more than one field with spaces or anything with linebreaks (e.g. tweet contents, profile description), it would get messy very quickly though and would require the `!r` conversion plus parsing again.
2. Use the API for that. No documentation exists currently, but see #73 for an example. The fields are the same: `tweet.user.id`, `tweet.date`, and `tweet.lang` (or `tweet.user.location`). The advantage of this is that you can put the data of interest directly into whichever data storage format you prefer instead of having to parse snscrape's output again.
