### ISSUE TITLE
Help with installation - libxml2 and libxslt

### ISSUE THREAD

**Issue by BluesFanUK** [JustAnotherArchivist/snscrape#983]
The introduction casually glazes over this, one of the dependencies is reliant on this - i've no idea where to even begin with getting those.

I'm on Python 3.9.14, Windows 10 64bit. I've tried to install those two via Pip but it says the following:
ERROR: Could not find a version that satisfies the requirement libxslt (from versions: none)
ERROR: No matching distribution found for libxslt

I'm guessing I need to manually obtain these somewhere? 

Thanks

**Comment by JustAnotherArchivist** [comment]
Yeah, this kind of thing is awful on Windows. I can't provide support for it. Please refer to [lxml's installation guide](https://lxml.de/installation.html) for some information; apparently there are binary builds of lxml for Windows which include libxml2 and libxslt. Possibly, those are the builds you get from PyPI.

(In case it wasn't obvious: these are not Python packages, you can't install them with pip or similar. That's also why it's mentioned in the readme, since you need to obtain those libraries in a different way, usually through your package manager on any Unixoid system that isn't macOS.)
