### ISSUE TITLE
multiprocessing

### ISSUE THREAD

**Issue by p-dre** [JustAnotherArchivist/snscrape#99]
My question is if several scrapers can be used in parallel?
I have tried to run them but there was an error and so I interessed if there is a limitation in this direction. 
I try the multiprocessing package. Is it possible that there are problems because both  be accessed via the cmd?

**Comment by JustAnotherArchivist** [comment]
Yes, you can run multiple snscrape processes in parallel. You might run into rate limit issues on some social networks (especially Instagram), but otherwise, I haven't seen any issues, though the most I ran against a single service was only 5-6. It's possible that higher parallelism causes problems.

I haven't tried with `multiprocessing`, but as long as you use separate `Scraper` objects for each scrape (either directly or by using the CLI via `subprocess`), I don't see a reason why that shouldn't work. Threads should also be sufficient.
